import { Product, Category, Review } from '@/types';

/**
 * Convertit un nom de produit en nom de fichier image
 * Supprime les accents pour correspondre aux noms de fichiers existants
 */
function productNameToImageName(name: string): string {
  // Mapping des caractères accentués vers leurs équivalents sans accent
  const accentMap: { [key: string]: string } = {
    'à': 'a', 'á': 'a', 'â': 'a', 'ã': 'a', 'ä': 'a', 'å': 'a',
    'è': 'e', 'é': 'e', 'ê': 'e', 'ë': 'e',
    'ì': 'i', 'í': 'i', 'î': 'i', 'ï': 'i',
    'ò': 'o', 'ó': 'o', 'ô': 'o', 'õ': 'o', 'ö': 'o',
    'ù': 'u', 'ú': 'u', 'û': 'u', 'ü': 'u',
    'ý': 'y', 'ÿ': 'y',
    'ç': 'c'
  };

  let result = name
    .toLowerCase()
    .trim()
    // Remplacer les caractères accentués
    .split('')
    .map(char => accentMap[char] || char)
    .join('')
    .replace(/\s+/g, '_')
    .replace(/[^a-z0-9_]/gi, '')
    .replace(/_{2,}/g, '_')
    .replace(/^_|_$/g, '') + '.jpg';

  // Mapping spécifique pour les fichiers existants avec noms différents
  const fileMapping: { [key: string]: string } = {
    // Cas où le fichier existe avec un nom légèrement différent
    'the_ritual_of_sakura_body_mist_rituals.jpg': 'he_ritual_of_sakura_body_mist_rituals.jpg',
    'the_ritual_of_ayurveda_eau_de_parfum_rituals.jpg': 'the_ritual_of_ayurveda_eau_de_parfum_ritual.jpg',
    'fructis_hydrating_garnier.jpg': 'fructis_hydrating_garnier..jpg'
  };

  // Si le résultat correspond à un mapping, utiliser le nom du fichier existant
  if (fileMapping[result]) {
    return fileMapping[result];
  }

  return result;
}

/**
 * Génère le chemin vers l’image d’un produit
 */
function getProductImagePath(productName: string): string {
  return `/image-products/${productNameToImageName(productName)}`;
}

export const categories: Category[] = [
  {
    id: '1',
    name: 'Soins du visage',
    slug: 'soins-visage',
    description: 'Crèmes, sérums, masques et produits de soin pour votre visage',
    image: getProductImagePath('Soins du visage'),
    subCategories: ['Crèmes hydratantes', 'Sérums', 'Masques', 'Nettoyants', 'Protection solaire']
  },
  {
    id: '2',
    name: 'Maquillage',
    slug: 'maquillage',
    description: 'Produits de maquillage pour sublimer votre beauté naturelle',
    image: getProductImagePath('Maquillage'),
    subCategories: ['Fond de teint', 'Rouge à lèvres', 'Mascara', 'Palettes', 'Highlighter']
  },
  {
    id: '3',
    name: 'Soins du corps',
    slug: 'soins-corps',
    description: 'Lotions, huiles et soins pour un corps radieux',
    image: getProductImagePath('Soins du corps'),
    subCategories: ['Lotions hydratantes', 'Huiles', 'Gommages', 'Soins des mains']
  },
  {
    id: '4',
    name: 'Cheveux',
    slug: 'cheveux',
    description: 'Shampoings, après-shampoings et soins capillaires',
    image: getProductImagePath('Cheveux'),
    subCategories: ['Shampoings', 'Après-shampoings', 'Masques', 'Soins coiffants']
  },
  {
    id: '5',
    name: 'Parfums',
    slug: 'parfums',
    description: 'Fragrances élégantes et raffinées',
    image: getProductImagePath('Parfums')
  },
  {
    id: '6',
    name: 'Accessoires beauté',
    slug: 'accessoires',
    description: 'Pinceaux, éponges et outils de beauté',
    image: getProductImagePath('Accessoires beauté')
  },
];

export const products: Product[] = [
  // SOINS VISAGE
  {
    id: '1',
    name: 'Buffet',
    description: 'Sérum multi-peptides pour réduire les signes de l’âge',
    longDescription: 'Sérum multi-peptides pour réduire les signes de l’âge. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.9,
    image: getProductImagePath('Buffet The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.1,
    reviewsCount: 51,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '2',
    name: 'Niacinamide 10% + Zinc 1%',
    description: 'Sérum niacinamide pour minimiser les pores',
    longDescription: 'Sérum niacinamide pour minimiser les pores. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.9,
    image: getProductImagePath('Niacinamide 10% + Zinc 1% The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.2,
    reviewsCount: 52,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '3',
    name: 'Hyaluronic Acid 2% + B5',
    description: 'Sérum acide hyaluronique hydratant',
    longDescription: 'Sérum acide hyaluronique hydratant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.9,
    image: getProductImagePath('Hyaluronic Acid 2% + B5 The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.3,
    reviewsCount: 53,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '4',
    name: 'Retinol 1% in Squalane',
    description: 'Sérum rétinol anti-âge',
    longDescription: 'Sérum rétinol anti-âge. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.9,
    image: getProductImagePath('Retinol 1% in Squalane The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.4,
    reviewsCount: 54,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '5',
    name: 'Vitamin C Suspension 23% + HA Spheres 2%',
    description: 'Sérum vitamine C éclat',
    longDescription: 'Sérum vitamine C éclat. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.9,
    image: getProductImagePath('Vitamin C Suspension 23% + HA Spheres 2% The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.5,
    reviewsCount: 55,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '6',
    name: 'AHA 30% + BHA 2% Peeling Solution',
    description: 'Masque peeling exfoliant',
    longDescription: 'Masque peeling exfoliant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.9,
    image: getProductImagePath('AHA 30% + BHA 2% Peeling Solution The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Masques',
    brand: 'The Ordinary',
    rating: 4.6,
    reviewsCount: 56,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '7',
    name: 'Revitalift Filler',
    description: 'Crème anti-âge repulpante',
    longDescription: 'Crème anti-âge repulpante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.99,
    image: getProductImagePath('Revitalift Filler L’Oréal Paris'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'L’Oréal Paris',
    rating: 4.7,
    reviewsCount: 57,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '8',
    name: 'Revitalift Laser X3',
    description: 'Crème anti-rides intensive',
    longDescription: 'Crème anti-rides intensive. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 39.99,
    image: getProductImagePath('Revitalift Laser X3 L’Oréal Paris'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'L’Oréal Paris',
    rating: 4.8,
    reviewsCount: 58,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '9',
    name: 'Age Perfect Cell Renewal',
    description: 'Crème régénérante mature',
    longDescription: 'Crème régénérante mature. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 44.99,
    image: getProductImagePath('Age Perfect Cell Renewal L’Oréal Paris'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'L’Oréal Paris',
    rating: 4.9,
    reviewsCount: 59,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '10',
    name: 'Hydra Genius',
    description: 'Crème hydratante légère',
    longDescription: 'Crème hydratante légère. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.99,
    image: getProductImagePath('Hydra Genius L’Oréal Paris'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'L’Oréal Paris',
    rating: 4.0,
    reviewsCount: 60,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '11',
    name: 'Pure Hyaluronic Acid Serum',
    description: 'Sérum acide hyaluronique pur',
    longDescription: 'Sérum acide hyaluronique pur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.9,
    image: getProductImagePath('Pure Hyaluronic Acid Serum The Inkey List'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Inkey List',
    rating: 4.1,
    reviewsCount: 61,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '12',
    name: 'Retinol Serum',
    description: 'Sérum rétinol concentré',
    longDescription: 'Sérum rétinol concentré. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.9,
    image: getProductImagePath('Retinol Serum The Inkey List'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Inkey List',
    rating: 4.2,
    reviewsCount: 62,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '13',
    name: 'Q10 Anti-Wrinkle Day Cream',
    description: 'Crème anti-rides jour',
    longDescription: 'Crème anti-rides jour. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Q10 Anti-Wrinkle Day Cream Nivea'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Nivea',
    rating: 4.3,
    reviewsCount: 63,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '14',
    name: 'Q10 Plus Anti-Age Night Cream',
    description: 'Crème anti-âge nuit',
    longDescription: 'Crème anti-âge nuit. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Q10 Plus Anti-Age Night Cream Nivea'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Nivea',
    rating: 4.4,
    reviewsCount: 64,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '15',
    name: 'Soft Moisturising Cream',
    description: 'Crème hydratante douce',
    longDescription: 'Crème hydratante douce. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Soft Moisturising Cream Nivea'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Nivea',
    rating: 4.5,
    reviewsCount: 65,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '16',
    name: 'The Ritual of Namaste',
    description: 'Crème visage ayurvédique',
    longDescription: 'Crème visage ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Namaste Rituals'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Rituals',
    rating: 4.6,
    reviewsCount: 66,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '17',
    name: 'The Ritual of Sakura',
    description: 'Crème hydratante cerisier',
    longDescription: 'Crème hydratante cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.95,
    image: getProductImagePath('The Ritual of Sakura Rituals'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Rituals',
    rating: 4.7,
    reviewsCount: 67,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '18',
    name: 'The Ritual of Karma',
    description: 'Crème anti-âge karma',
    longDescription: 'Crème anti-âge karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 36.95,
    image: getProductImagePath('The Ritual of Karma Rituals'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Rituals',
    rating: 4.8,
    reviewsCount: 68,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '19',
    name: 'Micellar Cleansing Water',
    description: 'Eau micellaire nettoyante',
    longDescription: 'Eau micellaire nettoyante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Micellar Cleansing Water Garnier'),
    category: 'soins-visage',
    subCategory: 'Nettoyants',
    brand: 'Garnier',
    rating: 4.9,
    reviewsCount: 69,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '20',
    name: 'Micellar Cleansing Gel',
    description: 'Gel nettoyant micellaire',
    longDescription: 'Gel nettoyant micellaire. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Micellar Cleansing Gel Garnier'),
    category: 'soins-visage',
    subCategory: 'Nettoyants',
    brand: 'Garnier',
    rating: 4.0,
    reviewsCount: 70,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '21',
    name: 'Vitamin C Brightening Serum',
    description: 'Sérum vitamine C éclat',
    longDescription: 'Sérum vitamine C éclat. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Vitamin C Brightening Serum Garnier'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'Garnier',
    rating: 4.1,
    reviewsCount: 71,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '22',
    name: 'Organic Argan Oil',
    description: 'Huile argan organique',
    longDescription: 'Huile argan organique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.9,
    image: getProductImagePath('Organic Argan Oil The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.2,
    reviewsCount: 72,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '23',
    name: '100% Plant-Derived Squalane',
    description: 'Huile squalane végétale',
    longDescription: 'Huile squalane végétale. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.9,
    image: getProductImagePath('100% Plant-Derived Squalane The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.3,
    reviewsCount: 73,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '24',
    name: 'Natural Moisturizing Factors + HA',
    description: 'Crème hydratante naturelle',
    longDescription: 'Crème hydratante naturelle. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.9,
    image: getProductImagePath('Natural Moisturizing Factors + HA The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'The Ordinary',
    rating: 4.4,
    reviewsCount: 74,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '25',
    name: 'Matrixyl 10% + HA',
    description: 'Sérum peptides anti-âge',
    longDescription: 'Sérum peptides anti-âge. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.9,
    image: getProductImagePath('Matrixyl 10% + HA The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.5,
    reviewsCount: 75,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '26',
    name: 'Argireline Solution 10%',
    description: 'Sérum anti-rides argireline',
    longDescription: 'Sérum anti-rides argireline. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.9,
    image: getProductImagePath('Argireline Solution 10% The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.6,
    reviewsCount: 76,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '27',
    name: 'Caffeine Solution 5% + EGCG',
    description: 'Sérum contour des yeux',
    longDescription: 'Sérum contour des yeux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.9,
    image: getProductImagePath('Caffeine Solution 5% + EGCG The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.7,
    reviewsCount: 77,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '28',
    name: 'Lactic Acid 10% + HA',
    description: 'Sérum acide lactique',
    longDescription: 'Sérum acide lactique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.9,
    image: getProductImagePath('Lactic Acid 10% + HA The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.8,
    reviewsCount: 78,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '29',
    name: 'Glycolic Acid 7% Toning Solution',
    description: 'Tonique acide glycolique',
    longDescription: 'Tonique acide glycolique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.9,
    image: getProductImagePath('Glycolic Acid 7% Toning Solution The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Nettoyants',
    brand: 'The Ordinary',
    rating: 4.9,
    reviewsCount: 79,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '30',
    name: 'Salicylic Acid 2% Solution',
    description: 'Sérum acide salicylique',
    longDescription: 'Sérum acide salicylique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.9,
    image: getProductImagePath('Salicylic Acid 2% Solution The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.0,
    reviewsCount: 80,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  // MAQUILLAGE
  {
    id: '31',
    name: 'True Match Foundation',
    description: 'Fond de teint correspondance parfaite',
    longDescription: 'Fond de teint correspondance parfaite. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('True Match Foundation L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.1,
    reviewsCount: 81,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '32',
    name: 'Infallible 24H Fresh Wear',
    description: 'Fond de teint longue tenue 24h',
    longDescription: 'Fond de teint longue tenue 24h. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Infallible 24H Fresh Wear L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.2,
    reviewsCount: 82,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '33',
    name: 'Age Perfect Foundation',
    description: 'Fond de teint mature',
    longDescription: 'Fond de teint mature. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.99,
    image: getProductImagePath('Age Perfect Foundation L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.3,
    reviewsCount: 83,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '34',
    name: 'Superstay Matte Ink',
    description: 'Rouge à lèvres liquide mat',
    longDescription: 'Rouge à lèvres liquide mat. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Superstay Matte Ink Maybelline'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'Maybelline',
    rating: 4.4,
    reviewsCount: 84,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '35',
    name: 'Color Sensational',
    description: 'Rouge à lèvres sensation couleur',
    longDescription: 'Rouge à lèvres sensation couleur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Color Sensational Maybelline'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'Maybelline',
    rating: 4.5,
    reviewsCount: 85,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '36',
    name: 'Lash Sensational Mascara',
    description: 'Mascara cils sensationnels',
    longDescription: 'Mascara cils sensationnels. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Lash Sensational Mascara Maybelline'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'Maybelline',
    rating: 4.6,
    reviewsCount: 86,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '37',
    name: 'The Falsies Mascara',
    description: 'Mascara volume faux cils',
    longDescription: 'Mascara volume faux cils. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('The Falsies Mascara Maybelline'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'Maybelline',
    rating: 4.7,
    reviewsCount: 87,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '38',
    name: 'Great Lash Mascara',
    description: 'Mascara grand cils',
    longDescription: 'Mascara grand cils. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Great Lash Mascara Maybelline'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'Maybelline',
    rating: 4.8,
    reviewsCount: 88,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '39',
    name: 'Fit Me! Foundation',
    description: 'Fond de teint ajusté',
    longDescription: 'Fond de teint ajusté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Fit Me! Foundation Maybelline'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Maybelline',
    rating: 4.9,
    reviewsCount: 89,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '40',
    name: 'Master Precise Liquid Eyeliner',
    description: 'Eyeliner liquide précis',
    longDescription: 'Eyeliner liquide précis. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Master Precise Liquid Eyeliner Maybelline'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Maybelline',
    rating: 4.0,
    reviewsCount: 90,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '41',
    name: 'Colorama Nail Polish',
    description: 'Vernis à ongles colorama',
    longDescription: 'Vernis à ongles colorama. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Colorama Nail Polish Maybelline'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Maybelline',
    rating: 4.1,
    reviewsCount: 91,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '42',
    name: 'Dream Satin Liquid Foundation',
    description: 'Fond de teint liquide satin',
    longDescription: 'Fond de teint liquide satin. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Dream Satin Liquid Foundation Maybelline'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Maybelline',
    rating: 4.2,
    reviewsCount: 92,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '43',
    name: 'Instant Age Rewind Concealer',
    description: 'Correcteur anti-âge',
    longDescription: 'Correcteur anti-âge. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Instant Age Rewind Concealer Maybelline'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Maybelline',
    rating: 4.3,
    reviewsCount: 93,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '44',
    name: 'Master Chrome Highlighter',
    description: 'Highlighter chrome',
    longDescription: 'Highlighter chrome. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Master Chrome Highlighter Maybelline'),
    category: 'maquillage',
    subCategory: 'Highlighter',
    brand: 'Maybelline',
    rating: 4.4,
    reviewsCount: 94,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '45',
    name: 'The Blushed Nudes Palette',
    description: 'Palette fards nude',
    longDescription: 'Palette fards nude. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('The Blushed Nudes Palette Maybelline'),
    category: 'maquillage',
    subCategory: 'Palettes',
    brand: 'Maybelline',
    rating: 4.5,
    reviewsCount: 95,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '46',
    name: 'The Nudes Palette',
    description: 'Palette nude',
    longDescription: 'Palette nude. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('The Nudes Palette Maybelline'),
    category: 'maquillage',
    subCategory: 'Palettes',
    brand: 'Maybelline',
    rating: 4.6,
    reviewsCount: 96,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '47',
    name: 'Color Riche Lipstick',
    description: 'Rouge à lèvres riche couleur',
    longDescription: 'Rouge à lèvres riche couleur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Color Riche Lipstick L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'L’Oréal Paris',
    rating: 4.7,
    reviewsCount: 97,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '48',
    name: 'Volume Million Lashes',
    description: 'Mascara million cils',
    longDescription: 'Mascara million cils. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Volume Million Lashes L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'L’Oréal Paris',
    rating: 4.8,
    reviewsCount: 98,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '49',
    name: 'Telescopic Mascara',
    description: 'Mascara télescopique',
    longDescription: 'Mascara télescopique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Telescopic Mascara L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'L’Oréal Paris',
    rating: 4.9,
    reviewsCount: 99,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '50',
    name: 'Liner Signature',
    description: 'Eyeliner signature',
    longDescription: 'Eyeliner signature. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Liner Signature L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.0,
    reviewsCount: 100,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '51',
    name: 'Blush Subtil',
    description: 'Blush subtil',
    longDescription: 'Blush subtil. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Blush Subtil L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.1,
    reviewsCount: 101,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '52',
    name: 'Glow Paradise',
    description: 'Baume à lèvres teinté',
    longDescription: 'Baume à lèvres teinté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Glow Paradise L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'L’Oréal Paris',
    rating: 4.2,
    reviewsCount: 102,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '53',
    name: 'Age Perfect Radiant Serum Foundation',
    description: 'Fond de teint sérum',
    longDescription: 'Fond de teint sérum. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.99,
    image: getProductImagePath('Age Perfect Radiant Serum Foundation L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.3,
    reviewsCount: 103,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '54',
    name: 'Infallible Pro-Matte Foundation',
    description: 'Fond de teint mat',
    longDescription: 'Fond de teint mat. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Infallible Pro-Matte Foundation L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.4,
    reviewsCount: 104,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '55',
    name: 'True Match Lumi Foundation',
    description: 'Fond de teint lumineux',
    longDescription: 'Fond de teint lumineux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('True Match Lumi Foundation L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.5,
    reviewsCount: 105,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '56',
    name: 'Infallible Pro-Last Lipstick',
    description: 'Rouge à lèvres longue tenue',
    longDescription: 'Rouge à lèvres longue tenue. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Infallible Pro-Last Lipstick L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'L’Oréal Paris',
    rating: 4.6,
    reviewsCount: 106,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '57',
    name: 'Color Riche Shine Lipstick',
    description: 'Rouge à lèvres brillant',
    longDescription: 'Rouge à lèvres brillant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Color Riche Shine Lipstick L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'L’Oréal Paris',
    rating: 4.7,
    reviewsCount: 107,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '58',
    name: 'Voluminous Lash Paradise Mascara',
    description: 'Mascara volume paradis',
    longDescription: 'Mascara volume paradis. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Voluminous Lash Paradise Mascara L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'L’Oréal Paris',
    rating: 4.8,
    reviewsCount: 108,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '59',
    name: 'Brow Stylist',
    description: 'Stylo sourcils',
    longDescription: 'Stylo sourcils. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Brow Stylist L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.9,
    reviewsCount: 109,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '60',
    name: 'Infallible Pro-Spray & Set',
    description: 'Fixateur maquillage',
    longDescription: 'Fixateur maquillage. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Infallible Pro-Spray & Set L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.0,
    reviewsCount: 110,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  // SOINS CORPS
  {
    id: '61',
    name: 'The Ritual of Namaste Body Cream',
    description: 'Crème corps ayurvédique',
    longDescription: 'Crème corps ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Namaste Body Cream Rituals'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Rituals',
    rating: 4.1,
    reviewsCount: 111,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '62',
    name: 'The Ritual of Sakura Body Cream',
    description: 'Crème corps cerisier',
    longDescription: 'Crème corps cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.95,
    image: getProductImagePath('The Ritual of Sakura Body Cream Rituals'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Rituals',
    rating: 4.2,
    reviewsCount: 112,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '63',
    name: 'The Ritual of Karma Body Cream',
    description: 'Crème corps karma',
    longDescription: 'Crème corps karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 36.95,
    image: getProductImagePath('The Ritual of Karma Body Cream Rituals'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Rituals',
    rating: 4.3,
    reviewsCount: 113,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '64',
    name: 'The Ritual of Ayurveda Body Cream',
    description: 'Crème corps ayurvéda',
    longDescription: 'Crème corps ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 35.95,
    image: getProductImagePath('The Ritual of Ayurveda Body Cream Rituals'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Rituals',
    rating: 4.4,
    reviewsCount: 114,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '65',
    name: 'The Ritual of Hammam Body Scrub',
    description: 'Gommage corps hammam',
    longDescription: 'Gommage corps hammam. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 38.95,
    image: getProductImagePath('The Ritual of Hammam Body Scrub Rituals'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Rituals',
    rating: 4.5,
    reviewsCount: 115,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '66',
    name: 'The Ritual of Namaste Body Scrub',
    description: 'Gommage corps ayurvédique',
    longDescription: 'Gommage corps ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 36.95,
    image: getProductImagePath('The Ritual of Namaste Body Scrub Rituals'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Rituals',
    rating: 4.6,
    reviewsCount: 116,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '67',
    name: 'The Ritual of Sakura Body Scrub',
    description: 'Gommage corps cerisier',
    longDescription: 'Gommage corps cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Sakura Body Scrub Rituals'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Rituals',
    rating: 4.7,
    reviewsCount: 117,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '68',
    name: 'The Ritual of Karma Body Scrub',
    description: 'Gommage corps karma',
    longDescription: 'Gommage corps karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 37.95,
    image: getProductImagePath('The Ritual of Karma Body Scrub Rituals'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Rituals',
    rating: 4.8,
    reviewsCount: 118,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '69',
    name: 'The Ritual of Ayurveda Body Scrub',
    description: 'Gommage corps ayurvéda',
    longDescription: 'Gommage corps ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 35.95,
    image: getProductImagePath('The Ritual of Ayurveda Body Scrub Rituals'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Rituals',
    rating: 4.9,
    reviewsCount: 119,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '70',
    name: 'The Ritual of Namaste Body Oil',
    description: 'Huile corps ayurvédique',
    longDescription: 'Huile corps ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 39.95,
    image: getProductImagePath('The Ritual of Namaste Body Oil Rituals'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Rituals',
    rating: 4.0,
    reviewsCount: 120,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '71',
    name: 'The Ritual of Sakura Body Oil',
    description: 'Huile corps cerisier',
    longDescription: 'Huile corps cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 37.95,
    image: getProductImagePath('The Ritual of Sakura Body Oil Rituals'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Rituals',
    rating: 4.1,
    reviewsCount: 121,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '72',
    name: 'The Ritual of Karma Body Oil',
    description: 'Huile corps karma',
    longDescription: 'Huile corps karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 41.95,
    image: getProductImagePath('The Ritual of Karma Body Oil Rituals'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Rituals',
    rating: 4.2,
    reviewsCount: 122,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '73',
    name: 'The Ritual of Ayurveda Body Oil',
    description: 'Huile corps ayurvéda',
    longDescription: 'Huile corps ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 38.95,
    image: getProductImagePath('The Ritual of Ayurveda Body Oil Rituals'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Rituals',
    rating: 4.3,
    reviewsCount: 123,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '74',
    name: 'The Ritual of Hammam Body Oil',
    description: 'Huile corps hammam',
    longDescription: 'Huile corps hammam. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 40.95,
    image: getProductImagePath('The Ritual of Hammam Body Oil Rituals'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Rituals',
    rating: 4.4,
    reviewsCount: 124,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '75',
    name: 'Nivea Body Lotion',
    description: 'Lotion corps hydratante',
    longDescription: 'Lotion corps hydratante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Nivea Body Lotion Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.5,
    reviewsCount: 125,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '76',
    name: 'Nivea Rich Nourishing Body Lotion',
    description: 'Lotion corps nourrissante',
    longDescription: 'Lotion corps nourrissante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Nivea Rich Nourishing Body Lotion Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.6,
    reviewsCount: 126,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '77',
    name: 'Nivea Soft Moisturising Cream',
    description: 'Crème corps douce',
    longDescription: 'Crème corps douce. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Nivea Soft Moisturising Cream Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.7,
    reviewsCount: 127,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '78',
    name: 'Nivea Q10 Plus Firming Body Lotion',
    description: 'Lotion corps fermeté',
    longDescription: 'Lotion corps fermeté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Nivea Q10 Plus Firming Body Lotion Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.8,
    reviewsCount: 128,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '79',
    name: 'Nivea Sun Protect & Moisture',
    description: 'Crème solaire hydratante',
    longDescription: 'Crème solaire hydratante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Nivea Sun Protect & Moisture Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.9,
    reviewsCount: 129,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '80',
    name: 'Nivea Sun Protect & Refresh',
    description: 'Spray solaire rafraîchissant',
    longDescription: 'Spray solaire rafraîchissant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Nivea Sun Protect & Refresh Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.0,
    reviewsCount: 130,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '81',
    name: 'Garnier Body Intensive 7 Days',
    description: 'Lotion corps 7 jours',
    longDescription: 'Lotion corps 7 jours. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Garnier Body Intensive 7 Days Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.1,
    reviewsCount: 131,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '82',
    name: 'Garnier Body Intensive Repair',
    description: 'Lotion corps réparatrice',
    longDescription: 'Lotion corps réparatrice. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Garnier Body Intensive Repair Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.2,
    reviewsCount: 132,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '83',
    name: 'Garnier Body Intensive Nourishing',
    description: 'Lotion corps nourrissante',
    longDescription: 'Lotion corps nourrissante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Garnier Body Intensive Nourishing Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.3,
    reviewsCount: 133,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '84',
    name: 'Garnier Body Intensive Smoothing',
    description: 'Lotion corps lissante',
    longDescription: 'Lotion corps lissante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Garnier Body Intensive Smoothing Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.4,
    reviewsCount: 134,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '85',
    name: 'Garnier Body Intensive Firming',
    description: 'Lotion corps fermeté',
    longDescription: 'Lotion corps fermeté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Garnier Body Intensive Firming Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.5,
    reviewsCount: 135,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '86',
    name: 'Garnier Body Intensive Anti-Age',
    description: 'Lotion corps anti-âge',
    longDescription: 'Lotion corps anti-âge. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Garnier Body Intensive Anti-Age Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.6,
    reviewsCount: 136,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '87',
    name: 'Garnier Body Intensive Sun Protection',
    description: 'Protection solaire corps',
    longDescription: 'Protection solaire corps. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Garnier Body Intensive Sun Protection Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.7,
    reviewsCount: 137,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '88',
    name: 'Garnier Body Intensive After Sun',
    description: 'Après-soleil apaisant',
    longDescription: 'Après-soleil apaisant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Garnier Body Intensive After Sun Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.8,
    reviewsCount: 138,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '89',
    name: 'Garnier Body Intensive Exfoliating',
    description: 'Gommage corps exfoliant',
    longDescription: 'Gommage corps exfoliant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Garnier Body Intensive Exfoliating Garnier'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Garnier',
    rating: 4.9,
    reviewsCount: 139,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '90',
    name: 'Garnier Body Intensive Hand Cream',
    description: 'Crème mains intensive',
    longDescription: 'Crème mains intensive. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Garnier Body Intensive Hand Cream Garnier'),
    category: 'soins-corps',
    subCategory: 'Soins des mains',
    brand: 'Garnier',
    rating: 4.0,
    reviewsCount: 140,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  // CHEVEUX
  {
    id: '91',
    name: 'Elvive Total Repair 5',
    description: 'Shampoing réparateur 5 actions',
    longDescription: 'Shampoing réparateur 5 actions. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Elvive Total Repair 5 L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.1,
    reviewsCount: 141,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '92',
    name: 'Elvive Dream Lengths',
    description: 'Shampoing longueur rêve',
    longDescription: 'Shampoing longueur rêve. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Elvive Dream Lengths L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.2,
    reviewsCount: 142,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '93',
    name: 'Elvive Extraordinary Oil',
    description: 'Huile capillaire extraordinaire',
    longDescription: 'Huile capillaire extraordinaire. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Elvive Extraordinary Oil L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Soins coiffants',
    brand: 'L’Oréal Paris',
    rating: 4.3,
    reviewsCount: 143,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '94',
    name: 'Elvive Color Vibrancy',
    description: 'Shampoing cheveux colorés',
    longDescription: 'Shampoing cheveux colorés. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Elvive Color Vibrancy L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.4,
    reviewsCount: 144,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '95',
    name: 'Elvive Volume Filler',
    description: 'Shampoing volume',
    longDescription: 'Shampoing volume. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Elvive Volume Filler L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.5,
    reviewsCount: 145,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '96',
    name: 'Elvive Smooth Intense',
    description: 'Shampoing lissant intense',
    longDescription: 'Shampoing lissant intense. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Elvive Smooth Intense L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.6,
    reviewsCount: 146,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '97',
    name: 'Elvive Nutri-Gloss',
    description: 'Shampoing brillance nutritif',
    longDescription: 'Shampoing brillance nutritif. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Elvive Nutri-Gloss L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.7,
    reviewsCount: 147,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '98',
    name: 'Elvive Fibrology',
    description: 'Shampoing densité',
    longDescription: 'Shampoing densité. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Elvive Fibrology L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.8,
    reviewsCount: 148,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '99',
    name: 'Elvive Hyaluron Plump',
    description: 'Shampoing hydratant hyaluron',
    longDescription: 'Shampoing hydratant hyaluron. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Elvive Hyaluron Plump L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.9,
    reviewsCount: 149,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '100',
    name: 'Elvive Wonder Water',
    description: 'Traitement capillaire eau',
    longDescription: 'Traitement capillaire eau. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 30.99,
    image: getProductImagePath('Elvive Wonder Water L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Masques',
    brand: 'L’Oréal Paris',
    rating: 4.0,
    reviewsCount: 150,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '101',
    name: 'Ultra Doux Shampoo',
    description: 'Shampoing ultra doux',
    longDescription: 'Shampoing ultra doux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Ultra Doux Shampoo Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.1,
    reviewsCount: 151,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '102',
    name: 'Ultra Doux Conditioner',
    description: 'Après-shampoing ultra doux',
    longDescription: 'Après-shampoing ultra doux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Ultra Doux Conditioner Garnier'),
    category: 'cheveux',
    subCategory: 'Après-shampoings',
    brand: 'Garnier',
    rating: 4.2,
    reviewsCount: 152,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '103',
    name: 'Ultra Doux Hair Mask',
    description: 'Masque capillaire ultra doux',
    longDescription: 'Masque capillaire ultra doux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Ultra Doux Hair Mask Garnier'),
    category: 'cheveux',
    subCategory: 'Masques',
    brand: 'Garnier',
    rating: 4.3,
    reviewsCount: 153,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '104',
    name: 'Ultra Doux Oil',
    description: 'Huile capillaire ultra doux',
    longDescription: 'Huile capillaire ultra doux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Ultra Doux Oil Garnier'),
    category: 'cheveux',
    subCategory: 'Soins coiffants',
    brand: 'Garnier',
    rating: 4.4,
    reviewsCount: 154,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '105',
    name: 'Fructis Strength & Shine',
    description: 'Shampoing force brillance',
    longDescription: 'Shampoing force brillance. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Fructis Strength & Shine Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.5,
    reviewsCount: 155,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '106',
    name: 'Fructis Smooth & Shine',
    description: 'Shampoing lissant brillance',
    longDescription: 'Shampoing lissant brillance. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Fructis Smooth & Shine Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.6,
    reviewsCount: 156,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '107',
    name: 'Fructis Volume & Body',
    description: 'Shampoing volume',
    longDescription: 'Shampoing volume. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Fructis Volume & Body Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.7,
    reviewsCount: 157,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '108',
    name: 'Fructis Color Shield',
    description: 'Shampoing protection couleur',
    longDescription: 'Shampoing protection couleur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Fructis Color Shield Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.8,
    reviewsCount: 158,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '109',
    name: 'Fructis Repair & Shine',
    description: 'Shampoing réparation brillance',
    longDescription: 'Shampoing réparation brillance. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Fructis Repair & Shine Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.9,
    reviewsCount: 159,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '110',
    name: 'Fructis Hydrating',
    description: 'Shampoing hydratant',
    longDescription: 'Shampoing hydratant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Fructis Hydrating Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.0,
    reviewsCount: 160,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '111',
    name: 'Nivea Hair Care Shampoo',
    description: 'Shampoing soin cheveux',
    longDescription: 'Shampoing soin cheveux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Nivea Hair Care Shampoo Nivea'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Nivea',
    rating: 4.1,
    reviewsCount: 161,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '112',
    name: 'Nivea Hair Care Conditioner',
    description: 'Après-shampoing soin',
    longDescription: 'Après-shampoing soin. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Nivea Hair Care Conditioner Nivea'),
    category: 'cheveux',
    subCategory: 'Après-shampoings',
    brand: 'Nivea',
    rating: 4.2,
    reviewsCount: 162,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '113',
    name: 'Nivea Hair Care Hair Mask',
    description: 'Masque capillaire soin',
    longDescription: 'Masque capillaire soin. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Nivea Hair Care Hair Mask Nivea'),
    category: 'cheveux',
    subCategory: 'Masques',
    brand: 'Nivea',
    rating: 4.3,
    reviewsCount: 163,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '114',
    name: 'Nivea Hair Care Oil',
    description: 'Huile capillaire soin',
    longDescription: 'Huile capillaire soin. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Nivea Hair Care Oil Nivea'),
    category: 'cheveux',
    subCategory: 'Soins coiffants',
    brand: 'Nivea',
    rating: 4.4,
    reviewsCount: 164,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '115',
    name: 'The Ritual of Namaste Shampoo',
    description: 'Shampoing ayurvédique',
    longDescription: 'Shampoing ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Namaste Shampoo Rituals'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Rituals',
    rating: 4.5,
    reviewsCount: 165,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '116',
    name: 'The Ritual of Sakura Shampoo',
    description: 'Shampoing cerisier',
    longDescription: 'Shampoing cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.95,
    image: getProductImagePath('The Ritual of Sakura Shampoo Rituals'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Rituals',
    rating: 4.6,
    reviewsCount: 166,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '117',
    name: 'The Ritual of Karma Shampoo',
    description: 'Shampoing karma',
    longDescription: 'Shampoing karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 36.95,
    image: getProductImagePath('The Ritual of Karma Shampoo Rituals'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Rituals',
    rating: 4.7,
    reviewsCount: 167,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '118',
    name: 'The Ritual of Ayurveda Shampoo',
    description: 'Shampoing ayurvéda',
    longDescription: 'Shampoing ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 35.95,
    image: getProductImagePath('The Ritual of Ayurveda Shampoo Rituals'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Rituals',
    rating: 4.8,
    reviewsCount: 168,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '119',
    name: 'The Ritual of Hammam Shampoo',
    description: 'Shampoing hammam',
    longDescription: 'Shampoing hammam. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 37.95,
    image: getProductImagePath('The Ritual of Hammam Shampoo Rituals'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Rituals',
    rating: 4.9,
    reviewsCount: 169,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '120',
    name: 'The Ritual of Namaste Conditioner',
    description: 'Après-shampoing ayurvédique',
    longDescription: 'Après-shampoing ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Namaste Conditioner Rituals'),
    category: 'cheveux',
    subCategory: 'Après-shampoings',
    brand: 'Rituals',
    rating: 4.0,
    reviewsCount: 170,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  // PARFUMS
  {
    id: '121',
    name: 'The Ritual of Namaste Eau de Parfum',
    description: 'Parfum ayurvédique',
    longDescription: 'Parfum ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 49.95,
    image: getProductImagePath('The Ritual of Namaste Eau de Parfum Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.1,
    reviewsCount: 171,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '122',
    name: 'The Ritual of Sakura Eau de Parfum',
    description: 'Parfum cerisier',
    longDescription: 'Parfum cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 47.95,
    image: getProductImagePath('The Ritual of Sakura Eau de Parfum Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.2,
    reviewsCount: 172,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '123',
    name: 'The Ritual of Karma Eau de Parfum',
    description: 'Parfum karma',
    longDescription: 'Parfum karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 51.95,
    image: getProductImagePath('The Ritual of Karma Eau de Parfum Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.3,
    reviewsCount: 173,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '124',
    name: 'The Ritual of Ayurveda Eau de Parfum',
    description: 'Parfum ayurvéda',
    longDescription: 'Parfum ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 49.95,
    image: getProductImagePath('The Ritual of Ayurveda Eau de Parfum Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.4,
    reviewsCount: 174,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '125',
    name: 'The Ritual of Hammam Eau de Parfum',
    description: 'Parfum hammam',
    longDescription: 'Parfum hammam. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 50.95,
    image: getProductImagePath('The Ritual of Hammam Eau de Parfum Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.5,
    reviewsCount: 175,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '126',
    name: 'The Ritual of Namaste Body Mist',
    description: 'Brume parfumée ayurvédique',
    longDescription: 'Brume parfumée ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Namaste Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.6,
    reviewsCount: 176,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '127',
    name: 'The Ritual of Sakura Body Mist',
    description: 'Brume parfumée cerisier',
    longDescription: 'Brume parfumée cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.95,
    image: getProductImagePath('The Ritual of Sakura Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.7,
    reviewsCount: 177,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '128',
    name: 'The Ritual of Karma Body Mist',
    description: 'Brume parfumée karma',
    longDescription: 'Brume parfumée karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 36.95,
    image: getProductImagePath('The Ritual of Karma Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.8,
    reviewsCount: 178,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '129',
    name: 'The Ritual of Ayurveda Body Mist',
    description: 'Brume parfumée ayurvéda',
    longDescription: 'Brume parfumée ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 35.95,
    image: getProductImagePath('The Ritual of Ayurveda Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.9,
    reviewsCount: 179,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '130',
    name: 'The Ritual of Hammam Body Mist',
    description: 'Brume parfumée hammam',
    longDescription: 'Brume parfumée hammam. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 37.95,
    image: getProductImagePath('The Ritual of Hammam Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.0,
    reviewsCount: 180,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '131',
    name: 'Nivea Deodorant',
    description: 'Déodorant protection',
    longDescription: 'Déodorant protection. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Nivea Deodorant Nivea'),
    category: 'parfums',
    subCategory: '',
    brand: 'Nivea',
    rating: 4.1,
    reviewsCount: 181,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '132',
    name: 'Nivea Roll-On',
    description: 'Déodorant roll-on',
    longDescription: 'Déodorant roll-on. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Nivea Roll-On Nivea'),
    category: 'parfums',
    subCategory: '',
    brand: 'Nivea',
    rating: 4.2,
    reviewsCount: 182,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '133',
    name: 'Nivea Spray',
    description: 'Déodorant spray',
    longDescription: 'Déodorant spray. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Nivea Spray Nivea'),
    category: 'parfums',
    subCategory: '',
    brand: 'Nivea',
    rating: 4.3,
    reviewsCount: 183,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '134',
    name: 'Garnier Deodorant',
    description: 'Déodorant fraîcheur',
    longDescription: 'Déodorant fraîcheur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Garnier Deodorant Garnier'),
    category: 'parfums',
    subCategory: '',
    brand: 'Garnier',
    rating: 4.4,
    reviewsCount: 184,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '135',
    name: 'Garnier Roll-On',
    description: 'Déodorant roll-on',
    longDescription: 'Déodorant roll-on. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Garnier Roll-On Garnier'),
    category: 'parfums',
    subCategory: '',
    brand: 'Garnier',
    rating: 4.5,
    reviewsCount: 185,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '136',
    name: 'Garnier Spray',
    description: 'Déodorant spray',
    longDescription: 'Déodorant spray. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Garnier Spray Garnier'),
    category: 'parfums',
    subCategory: '',
    brand: 'Garnier',
    rating: 4.6,
    reviewsCount: 186,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '137',
    name: 'L’Oréal Paris Deodorant',
    description: 'Déodorant protection',
    longDescription: 'Déodorant protection. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('L’Oréal Paris Deodorant L’Oréal Paris'),
    category: 'parfums',
    subCategory: '',
    brand: 'L’Oréal Paris',
    rating: 4.7,
    reviewsCount: 187,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '138',
    name: 'L’Oréal Paris Roll-On',
    description: 'Déodorant roll-on',
    longDescription: 'Déodorant roll-on. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('L’Oréal Paris Roll-On L’Oréal Paris'),
    category: 'parfums',
    subCategory: '',
    brand: 'L’Oréal Paris',
    rating: 4.8,
    reviewsCount: 188,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '139',
    name: 'L’Oréal Paris Spray',
    description: 'Déodorant spray',
    longDescription: 'Déodorant spray. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('L’Oréal Paris Spray L’Oréal Paris'),
    category: 'parfums',
    subCategory: '',
    brand: 'L’Oréal Paris',
    rating: 4.9,
    reviewsCount: 189,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '140',
    name: 'Rexona Maximum Protection',
    description: 'Déodorant protection maximale',
    longDescription: 'Déodorant protection maximale 48h. Formule anti-transpirante efficace. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Rexona Maximum Protection Rexona'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rexona',
    rating: 4.0,
    reviewsCount: 190,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '141',
    name: 'Rexona Roll-On',
    description: 'Déodorant roll-on fraîcheur',
    longDescription: 'Déodorant roll-on fraîcheur longue durée. Application douce et efficace. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Rexona Roll-On Rexona'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rexona',
    rating: 4.1,
    reviewsCount: 191,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '142',
    name: 'Rexona Spray',
    description: 'Déodorant spray invisible',
    longDescription: 'Déodorant spray invisible protection 48h. Ne laisse pas de traces blanches. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Rexona Spray Rexona'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rexona',
    rating: 4.2,
    reviewsCount: 192,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '143',
    name: 'Sanex Dermo Sensitive',
    description: 'Déodorant peaux sensibles',
    longDescription: 'Déodorant pour peaux sensibles sans parfum ni alcool. Formule douce et hypoallergénique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Sanex Dermo Sensitive Sanex'),
    category: 'parfums',
    subCategory: '',
    brand: 'Sanex',
    rating: 4.3,
    reviewsCount: 193,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '144',
    name: 'Dove Original',
    description: 'Déodorant soin et protection',
    longDescription: 'Déodorant avec 1/4 de crème hydratante. Protection 48h et soin de la peau. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Dove Original Dove'),
    category: 'parfums',
    subCategory: '',
    brand: 'Dove',
    rating: 4.4,
    reviewsCount: 194,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '145',
    name: 'Yves Rocher Déodorant Nature',
    description: 'Déodorant naturel bio',
    longDescription: 'Déodorant naturel certifié bio aux extraits de plantes. Formule respectueuse de la peau. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.95,
    image: getProductImagePath('Yves Rocher Déodorant Nature Yves Rocher'),
    category: 'parfums',
    subCategory: '',
    brand: 'Yves Rocher',
    rating: 4.5,
    reviewsCount: 195,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '146',
    name: 'Yves Rocher Roll-On Végétal',
    description: 'Déodorant roll-on végétal',
    longDescription: 'Déodorant roll-on à base d\'ingrédients végétaux. Protection efficace et douceur garantie. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 30.95,
    image: getProductImagePath('Yves Rocher Roll-On Végétal Yves Rocher'),
    category: 'parfums',
    subCategory: '',
    brand: 'Yves Rocher',
    rating: 4.6,
    reviewsCount: 196,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '147',
    name: 'Yves Rocher Spray Fraîcheur',
    description: 'Déodorant spray fraîcheur',
    longDescription: 'Déodorant spray fraîcheur instantanée. Formule légère et rafraîchissante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 31.95,
    image: getProductImagePath('Yves Rocher Spray Fraîcheur Yves Rocher'),
    category: 'parfums',
    subCategory: '',
    brand: 'Yves Rocher',
    rating: 4.7,
    reviewsCount: 197,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '148',
    name: 'Yves Rocher Brume Parfumée',
    description: 'Brume parfumée corps',
    longDescription: 'Brume parfumée pour le corps aux notes florales. Légère et enveloppante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 33.95,
    image: getProductImagePath('Yves Rocher Brume Parfumée Yves Rocher'),
    category: 'parfums',
    subCategory: '',
    brand: 'Yves Rocher',
    rating: 4.8,
    reviewsCount: 198,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '149',
    name: 'Yves Rocher Eau de Toilette',
    description: 'Eau de toilette signature',
    longDescription: 'Eau de toilette signature aux essences naturelles. Fragrance élégante et durable. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 45.95,
    image: getProductImagePath('Yves Rocher Eau de Toilette Yves Rocher'),
    category: 'parfums',
    subCategory: '',
    brand: 'Yves Rocher',
    rating: 4.9,
    reviewsCount: 199,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '150',
    name: 'Yves Rocher Eau de Cologne',
    description: 'Eau de cologne rafraîchissante',
    longDescription: 'Eau de cologne rafraîchissante aux agrumes. Parfum léger et tonifiant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 43.95,
    image: getProductImagePath('Yves Rocher Eau de Cologne Yves Rocher'),
    category: 'parfums',
    subCategory: '',
    brand: 'Yves Rocher',
    rating: 4.0,
    reviewsCount: 200,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  // ACCESSOIRES
  {
    id: '151',
    name: 'Essential Brush Set',
    description: 'Set pinceaux essentiels',
    longDescription: 'Set de 6 pinceaux essentiels pour le maquillage. Poils synthétiques doux et résistants. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 35.99,
    image: getProductImagePath('Essential Brush Set EcoTools'),
    category: 'accessoires',
    subCategory: '',
    brand: 'EcoTools',
    rating: 4.1,
    reviewsCount: 201,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '152',
    name: 'Perfecting Blender Sponge',
    description: 'Éponge beauté parfaite',
    longDescription: 'Éponge beauté pour un fini parfait. Forme ergonomique et texture douce. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Perfecting Blender Sponge EcoTools'),
    category: 'accessoires',
    subCategory: '',
    brand: 'EcoTools',
    rating: 4.2,
    reviewsCount: 202,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '153',
    name: 'LED Makeup Mirror',
    description: 'Miroir maquillage LED',
    longDescription: 'Miroir maquillage LED avec éclairage réglable. 3 niveaux d\'intensité et miroir grossissant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 94.99,
    image: getProductImagePath('LED Makeup Mirror Philips'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Philips',
    rating: 4.3,
    reviewsCount: 203,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '154',
    name: 'Brush Storage Case',
    description: 'Étui de rangement pinceaux',
    longDescription: 'Étui de rangement pour pinceaux avec compartiments. Design compact et pratique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Brush Storage Case EcoTools'),
    category: 'accessoires',
    subCategory: '',
    brand: 'EcoTools',
    rating: 4.4,
    reviewsCount: 204,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '155',
    name: 'Beauty Organizer',
    description: 'Organisateur beauté',
    longDescription: 'Organisateur beauté avec compartiments multiples. Design élégant et fonctionnel. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 54.99,
    image: getProductImagePath('Beauty Organizer Philips'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Philips',
    rating: 4.5,
    reviewsCount: 205,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '156',
    name: 'Travel Makeup Bag',
    description: 'Trousse maquillage voyage',
    longDescription: 'Trousse maquillage voyage avec poches multiples. Matériau résistant et imperméable. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Travel Makeup Bag EcoTools'),
    category: 'accessoires',
    subCategory: '',
    brand: 'EcoTools',
    rating: 4.6,
    reviewsCount: 206,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '157',
    name: 'Brush Cleansing Soap',
    description: 'Savon nettoyant pinceaux',
    longDescription: 'Savon nettoyant pour pinceaux. Formule douce et efficace. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Brush Cleansing Soap EcoTools'),
    category: 'accessoires',
    subCategory: '',
    brand: 'EcoTools',
    rating: 4.7,
    reviewsCount: 207,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '158',
    name: 'Reusable Makeup Remover Pads',
    description: 'Disques démaquillants réutilisables',
    longDescription: 'Disques démaquillants réutilisables en coton bio. Doux pour la peau et écologiques. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Reusable Makeup Remover Pads EcoTools'),
    category: 'accessoires',
    subCategory: '',
    brand: 'EcoTools',
    rating: 4.8,
    reviewsCount: 208,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '159',
    name: 'Professional Eyelash Curler',
    description: 'Recourbe-cils professionnel',
    longDescription: 'Recourbe-cils professionnel avec coussinets rembourrés. Design ergonomique et efficace. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Professional Eyelash Curler Shiseido'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Shiseido',
    rating: 4.9,
    reviewsCount: 209,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '160',
    name: 'Precision Tweezers',
    description: 'Pince à épiler précision',
    longDescription: 'Pince à épiler précision avec pointe fine. Prise en main confortable. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Precision Tweezers Shiseido'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Shiseido',
    rating: 4.0,
    reviewsCount: 210,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '161',
    name: 'Professional Nail Care Set',
    description: 'Set soin ongles professionnel',
    longDescription: 'Set soin ongles professionnel complet. Outils de qualité et durables. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Professional Nail Care Set Shiseido'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Shiseido',
    rating: 4.1,
    reviewsCount: 211,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '162',
    name: 'Wet Brush Pro',
    description: 'Brosse cheveux humide',
    longDescription: 'Brosse cheveux pour cheveux mouillés. Démêle sans casser les cheveux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Wet Brush Pro Wet Brush'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Wet Brush',
    rating: 4.2,
    reviewsCount: 212,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '163',
    name: 'Detangler Brush',
    description: 'Brosse démêlante professionnelle',
    longDescription: 'Brosse démêlante professionnelle. Poils flexibles et doux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Detangler Brush Wet Brush'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Wet Brush',
    rating: 4.3,
    reviewsCount: 213,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '164',
    name: 'Ionic Hair Dryer',
    description: 'Sèche-cheveux ionique',
    longDescription: 'Sèche-cheveux ionique avec technologie infrarouge. Séchage rapide et soin des cheveux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 94.99,
    image: getProductImagePath('Ionic Hair Dryer Babyliss'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Babyliss',
    rating: 4.4,
    reviewsCount: 214,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '165',
    name: 'Ceramic Straightener',
    description: 'Lisseur céramique',
    longDescription: 'Lisseur céramique avec plaques lissantes. Température réglable jusqu\'à 230°C. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 84.99,
    image: getProductImagePath('Ceramic Straightener Babyliss'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Babyliss',
    rating: 4.5,
    reviewsCount: 215,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '166',
    name: 'Curling Wand',
    description: 'Fer à boucler',
    longDescription: 'Fer à boucler avec baril en céramique. Crée des boucles durables et naturelles. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 74.99,
    image: getProductImagePath('Curling Wand Babyliss'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Babyliss',
    rating: 4.6,
    reviewsCount: 216,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '167',
    name: 'Hair Claw Clips',
    description: 'Pinces griffes cheveux',
    longDescription: 'Pinces griffes pour cheveux. Design moderne et résistant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Hair Claw Clips Scünci'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Scünci',
    rating: 4.7,
    reviewsCount: 217,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '168',
    name: 'No-Crease Hair Elastics',
    description: 'Élastiques cheveux sans marque',
    longDescription: 'Élastiques cheveux sans marque. Ne laisse pas de trace et ne casse pas les cheveux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('No-Crease Hair Elastics Scünci'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Scünci',
    rating: 4.8,
    reviewsCount: 218,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '169',
    name: 'Velvet Scrunchie',
    description: 'Chouchou velours',
    longDescription: 'Chouchou en velours doux. Design élégant et confortable. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Velvet Scrunchie Scünci'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Scünci',
    rating: 4.9,
    reviewsCount: 219,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '170',
    name: 'Wide Headband',
    description: 'Bandeau large',
    longDescription: 'Bandeau large en tissu doux. Tient bien en place et confortable. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Wide Headband Scünci'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Scünci',
    rating: 4.0,
    reviewsCount: 220,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '171',
    name: 'Magnetic Makeup Palette',
    description: 'Palette maquillage magnétique',
    longDescription: 'Palette maquillage magnétique avec compartiments amovibles. Design pratique et modulaire. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 35.99,
    image: getProductImagePath('Magnetic Makeup Palette Morphe'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Morphe',
    rating: 4.1,
    reviewsCount: 221,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '172',
    name: 'Pro Brush Collection',
    description: 'Collection pinceaux pro',
    longDescription: 'Collection complète de pinceaux professionnels. 12 pinceaux de qualité supérieure. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 94.99,
    image: getProductImagePath('Pro Brush Collection Morphe'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Morphe',
    rating: 4.2,
    reviewsCount: 222,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '173',
    name: 'Original Beauty Sponge',
    description: 'Éponge beauté originale',
    longDescription: 'Éponge beauté originale pour un fini sans défaut. Forme unique et texture douce. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Original Beauty Sponge Fenty Beauty'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Fenty Beauty',
    rating: 4.3,
    reviewsCount: 223,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '174',
    name: 'Beauty Sponge Duo',
    description: 'Duo éponges beauté',
    longDescription: 'Duo éponges beauté avec deux tailles. Parfait pour tous les types de maquillage. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 54.99,
    image: getProductImagePath('Beauty Sponge Duo Fenty Beauty'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Fenty Beauty',
    rating: 4.4,
    reviewsCount: 224,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '175',
    name: 'Brush Cleaning Glove',
    description: 'Gant nettoyant pinceaux',
    longDescription: 'Gant nettoyant pour pinceaux avec textures différentes. Nettoyage efficace et rapide. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 30.99,
    image: getProductImagePath('Brush Cleaning Glove Morphe'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Morphe',
    rating: 4.5,
    reviewsCount: 225,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '176',
    name: 'Essential Brush Kit',
    description: 'Kit pinceaux essentiels',
    longDescription: 'Kit de 8 pinceaux essentiels pour le maquillage. Poils synthétiques de qualité. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 84.99,
    image: getProductImagePath('Essential Brush Kit Morphe'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Morphe',
    rating: 4.6,
    reviewsCount: 226,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '177',
    name: 'Blending Sponge',
    description: 'Éponge de fusion',
    longDescription: 'Éponge de fusion pour un maquillage sans couture. Texture unique et forme ergonomique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Blending Sponge Morphe'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Morphe',
    rating: 4.7,
    reviewsCount: 227,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '178',
    name: 'Compact Makeup Mirror',
    description: 'Miroir maquillage compact',
    longDescription: 'Miroir maquillage compact avec éclairage LED. Parfait pour le voyage. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 64.99,
    image: getProductImagePath('Compact Makeup Mirror Philips'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Philips',
    rating: 4.8,
    reviewsCount: 228,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '179',
    name: 'Smart LED Mirror',
    description: 'Miroir LED intelligent',
    longDescription: 'Miroir LED intelligent avec détection automatique. Éclairage naturel et réglable. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 74.99,
    image: getProductImagePath('Smart LED Mirror Philips'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Philips',
    rating: 4.9,
    reviewsCount: 229,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '180',
    name: 'Portable Mirror',
    description: 'Miroir portable',
    longDescription: 'Miroir portable avec éclairage LED intégré. Design compact et pratique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 30.99,
    image: getProductImagePath('Portable Mirror Philips'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Philips',
    rating: 4.0,
    reviewsCount: 230,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    productId: '1',
    userName: 'Sophie M.',
    rating: 5,
    comment: 'Excellent produit ! Ma peau est visiblement plus radieuse après seulement 2 semaines d’utilisation.',
    date: '2024-01-15',
    verified: true
  },
  {
    id: '2',
    productId: '1',
    userName: 'Emma L.',
    rating: 5,
    comment: 'Je recommande vivement ce sérum. Texture agréable et résultats impressionnants.',
    date: '2024-01-10',
    verified: true
  },
  {
    id: '3',
    productId: '24',
    userName: 'Léa D.',
    rating: 5,
    comment: 'Ma couleur préférée ! Tenue exceptionnelle et texture très confortable.',
    date: '2024-01-20',
    verified: true
  },
  {
    id: '4',
    productId: '20',
    userName: 'Camille R.',
    rating: 5,
    comment: 'Fond de teint parfait ! Couvrance excellente et tenue toute la journée.',
    date: '2024-01-22',
    verified: true
  },
  {
    id: '5',
    productId: '37',
    userName: 'Marie K.',
    rating: 5,
    comment: 'Lotion super hydratante, ma peau est douce comme la soie !',
    date: '2024-01-18',
    verified: true
  },
];

