import { Product, Category, Review } from '@/types';

/**
 * Convertit un nom de produit en nom de fichier image
 */
function productNameToImageName(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '_')
    .replace(/[^a-z0-9_àáâãäåèéêëìíîïòóôõöùúûüýÿç]/gi, '')
    .replace(/_{2,}/g, '_')
    .replace(/^_|_$/g, '') + '.jpg';
}

/**
 * Génère le chemin vers l’image d’un produit
 */
function getProductImagePath(productName: string): string {
  return `/image-products/${productNameToImageName(productName)}`;
}

export const categories: Category[] = [
  {
    id: '1',
    name: 'Soins du visage',
    slug: 'soins-visage',
    description: 'Crèmes, sérums, masques et produits de soin pour votre visage',
    image: getProductImagePath('Soins du visage'),
    subCategories: ['Crèmes hydratantes', 'Sérums', 'Masques', 'Nettoyants', 'Protection solaire']
  },
  {
    id: '2',
    name: 'Maquillage',
    slug: 'maquillage',
    description: 'Produits de maquillage pour sublimer votre beauté naturelle',
    image: getProductImagePath('Maquillage'),
    subCategories: ['Fond de teint', 'Rouge à lèvres', 'Mascara', 'Palettes', 'Highlighter']
  },
  {
    id: '3',
    name: 'Soins du corps',
    slug: 'soins-corps',
    description: 'Lotions, huiles et soins pour un corps radieux',
    image: getProductImagePath('Soins du corps'),
    subCategories: ['Lotions hydratantes', 'Huiles', 'Gommages', 'Soins des mains']
  },
  {
    id: '4',
    name: 'Cheveux',
    slug: 'cheveux',
    description: 'Shampoings, après-shampoings et soins capillaires',
    image: getProductImagePath('Cheveux'),
    subCategories: ['Shampoings', 'Après-shampoings', 'Masques', 'Soins coiffants']
  },
  {
    id: '5',
    name: 'Parfums',
    slug: 'parfums',
    description: 'Fragrances élégantes et raffinées',
    image: getProductImagePath('Parfums')
  },
  {
    id: '6',
    name: 'Accessoires beauté',
    slug: 'accessoires',
    description: 'Pinceaux, éponges et outils de beauté',
    image: getProductImagePath('Accessoires beauté')
  },
];

export const products: Product[] = [
  // SOINS VISAGE
  {
    id: '1',
    name: 'Buffet',
    description: 'Sérum multi-peptides pour réduire les signes de l’âge',
    longDescription: 'Sérum multi-peptides pour réduire les signes de l’âge. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.9,
    image: getProductImagePath('Buffet The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.1,
    reviewsCount: 51,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '2',
    name: 'Niacinamide 10% + Zinc 1%',
    description: 'Sérum niacinamide pour minimiser les pores',
    longDescription: 'Sérum niacinamide pour minimiser les pores. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.9,
    image: getProductImagePath('Niacinamide 10% + Zinc 1% The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.2,
    reviewsCount: 52,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '3',
    name: 'Hyaluronic Acid 2% + B5',
    description: 'Sérum acide hyaluronique hydratant',
    longDescription: 'Sérum acide hyaluronique hydratant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.9,
    image: getProductImagePath('Hyaluronic Acid 2% + B5 The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.3,
    reviewsCount: 53,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '4',
    name: 'Retinol 1% in Squalane',
    description: 'Sérum rétinol anti-âge',
    longDescription: 'Sérum rétinol anti-âge. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.9,
    image: getProductImagePath('Retinol 1% in Squalane The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.4,
    reviewsCount: 54,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '5',
    name: 'Vitamin C Suspension 23% + HA Spheres 2%',
    description: 'Sérum vitamine C éclat',
    longDescription: 'Sérum vitamine C éclat. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.9,
    image: getProductImagePath('Vitamin C Suspension 23% + HA Spheres 2% The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.5,
    reviewsCount: 55,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '6',
    name: 'AHA 30% + BHA 2% Peeling Solution',
    description: 'Masque peeling exfoliant',
    longDescription: 'Masque peeling exfoliant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.9,
    image: getProductImagePath('AHA 30% + BHA 2% Peeling Solution The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Masques',
    brand: 'The Ordinary',
    rating: 4.6,
    reviewsCount: 56,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '7',
    name: 'Revitalift Filler',
    description: 'Crème anti-âge repulpante',
    longDescription: 'Crème anti-âge repulpante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.99,
    image: getProductImagePath('Revitalift Filler L’Oréal Paris'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'L’Oréal Paris',
    rating: 4.7,
    reviewsCount: 57,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '8',
    name: 'Revitalift Laser X3',
    description: 'Crème anti-rides intensive',
    longDescription: 'Crème anti-rides intensive. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 39.99,
    image: getProductImagePath('Revitalift Laser X3 L’Oréal Paris'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'L’Oréal Paris',
    rating: 4.8,
    reviewsCount: 58,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '9',
    name: 'Age Perfect Cell Renewal',
    description: 'Crème régénérante mature',
    longDescription: 'Crème régénérante mature. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 44.99,
    image: getProductImagePath('Age Perfect Cell Renewal L’Oréal Paris'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'L’Oréal Paris',
    rating: 4.9,
    reviewsCount: 59,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '10',
    name: 'Hydra Genius',
    description: 'Crème hydratante légère',
    longDescription: 'Crème hydratante légère. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.99,
    image: getProductImagePath('Hydra Genius L’Oréal Paris'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'L’Oréal Paris',
    rating: 4.0,
    reviewsCount: 60,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '11',
    name: 'Pure Hyaluronic Acid Serum',
    description: 'Sérum acide hyaluronique pur',
    longDescription: 'Sérum acide hyaluronique pur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.9,
    image: getProductImagePath('Pure Hyaluronic Acid Serum The Inkey List'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Inkey List',
    rating: 4.1,
    reviewsCount: 61,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '12',
    name: 'Retinol Serum',
    description: 'Sérum rétinol concentré',
    longDescription: 'Sérum rétinol concentré. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.9,
    image: getProductImagePath('Retinol Serum The Inkey List'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Inkey List',
    rating: 4.2,
    reviewsCount: 62,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '13',
    name: 'Q10 Anti-Wrinkle Day Cream',
    description: 'Crème anti-rides jour',
    longDescription: 'Crème anti-rides jour. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Q10 Anti-Wrinkle Day Cream Nivea'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Nivea',
    rating: 4.3,
    reviewsCount: 63,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '14',
    name: 'Q10 Plus Anti-Age Night Cream',
    description: 'Crème anti-âge nuit',
    longDescription: 'Crème anti-âge nuit. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Q10 Plus Anti-Age Night Cream Nivea'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Nivea',
    rating: 4.4,
    reviewsCount: 64,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '15',
    name: 'Soft Moisturising Cream',
    description: 'Crème hydratante douce',
    longDescription: 'Crème hydratante douce. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Soft Moisturising Cream Nivea'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Nivea',
    rating: 4.5,
    reviewsCount: 65,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '16',
    name: 'The Ritual of Namaste',
    description: 'Crème visage ayurvédique',
    longDescription: 'Crème visage ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Namaste Rituals'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Rituals',
    rating: 4.6,
    reviewsCount: 66,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '17',
    name: 'The Ritual of Sakura',
    description: 'Crème hydratante cerisier',
    longDescription: 'Crème hydratante cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.95,
    image: getProductImagePath('The Ritual of Sakura Rituals'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Rituals',
    rating: 4.7,
    reviewsCount: 67,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '18',
    name: 'The Ritual of Karma',
    description: 'Crème anti-âge karma',
    longDescription: 'Crème anti-âge karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 36.95,
    image: getProductImagePath('The Ritual of Karma Rituals'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Rituals',
    rating: 4.8,
    reviewsCount: 68,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '19',
    name: 'Micellar Cleansing Water',
    description: 'Eau micellaire nettoyante',
    longDescription: 'Eau micellaire nettoyante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Micellar Cleansing Water Garnier'),
    category: 'soins-visage',
    subCategory: 'Nettoyants',
    brand: 'Garnier',
    rating: 4.9,
    reviewsCount: 69,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '20',
    name: 'Micellar Cleansing Gel',
    description: 'Gel nettoyant micellaire',
    longDescription: 'Gel nettoyant micellaire. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Micellar Cleansing Gel Garnier'),
    category: 'soins-visage',
    subCategory: 'Nettoyants',
    brand: 'Garnier',
    rating: 4.0,
    reviewsCount: 70,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '21',
    name: 'Vitamin C Brightening Serum',
    description: 'Sérum vitamine C éclat',
    longDescription: 'Sérum vitamine C éclat. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Vitamin C Brightening Serum Garnier'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'Garnier',
    rating: 4.1,
    reviewsCount: 71,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '22',
    name: 'Organic Argan Oil',
    description: 'Huile argan organique',
    longDescription: 'Huile argan organique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.9,
    image: getProductImagePath('Organic Argan Oil The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.2,
    reviewsCount: 72,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '23',
    name: '100% Plant-Derived Squalane',
    description: 'Huile squalane végétale',
    longDescription: 'Huile squalane végétale. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.9,
    image: getProductImagePath('100% Plant-Derived Squalane The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.3,
    reviewsCount: 73,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '24',
    name: 'Natural Moisturizing Factors + HA',
    description: 'Crème hydratante naturelle',
    longDescription: 'Crème hydratante naturelle. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.9,
    image: getProductImagePath('Natural Moisturizing Factors + HA The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'The Ordinary',
    rating: 4.4,
    reviewsCount: 74,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '25',
    name: 'Matrixyl 10% + HA',
    description: 'Sérum peptides anti-âge',
    longDescription: 'Sérum peptides anti-âge. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.9,
    image: getProductImagePath('Matrixyl 10% + HA The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.5,
    reviewsCount: 75,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '26',
    name: 'Argireline Solution 10%',
    description: 'Sérum anti-rides argireline',
    longDescription: 'Sérum anti-rides argireline. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.9,
    image: getProductImagePath('Argireline Solution 10% The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.6,
    reviewsCount: 76,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '27',
    name: 'Caffeine Solution 5% + EGCG',
    description: 'Sérum contour des yeux',
    longDescription: 'Sérum contour des yeux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.9,
    image: getProductImagePath('Caffeine Solution 5% + EGCG The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.7,
    reviewsCount: 77,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '28',
    name: 'Lactic Acid 10% + HA',
    description: 'Sérum acide lactique',
    longDescription: 'Sérum acide lactique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.9,
    image: getProductImagePath('Lactic Acid 10% + HA The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.8,
    reviewsCount: 78,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '29',
    name: 'Glycolic Acid 7% Toning Solution',
    description: 'Tonique acide glycolique',
    longDescription: 'Tonique acide glycolique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.9,
    image: getProductImagePath('Glycolic Acid 7% Toning Solution The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Nettoyants',
    brand: 'The Ordinary',
    rating: 4.9,
    reviewsCount: 79,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '30',
    name: 'Salicylic Acid 2% Solution',
    description: 'Sérum acide salicylique',
    longDescription: 'Sérum acide salicylique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.9,
    image: getProductImagePath('Salicylic Acid 2% Solution The Ordinary'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'The Ordinary',
    rating: 4.0,
    reviewsCount: 80,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  // MAQUILLAGE
  {
    id: '31',
    name: 'True Match Foundation',
    description: 'Fond de teint correspondance parfaite',
    longDescription: 'Fond de teint correspondance parfaite. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('True Match Foundation L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.1,
    reviewsCount: 81,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '32',
    name: 'Infallible 24H Fresh Wear',
    description: 'Fond de teint longue tenue 24h',
    longDescription: 'Fond de teint longue tenue 24h. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Infallible 24H Fresh Wear L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.2,
    reviewsCount: 82,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '33',
    name: 'Age Perfect Foundation',
    description: 'Fond de teint mature',
    longDescription: 'Fond de teint mature. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.99,
    image: getProductImagePath('Age Perfect Foundation L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.3,
    reviewsCount: 83,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '34',
    name: 'Superstay Matte Ink',
    description: 'Rouge à lèvres liquide mat',
    longDescription: 'Rouge à lèvres liquide mat. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Superstay Matte Ink Maybelline'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'Maybelline',
    rating: 4.4,
    reviewsCount: 84,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '35',
    name: 'Color Sensational',
    description: 'Rouge à lèvres sensation couleur',
    longDescription: 'Rouge à lèvres sensation couleur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Color Sensational Maybelline'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'Maybelline',
    rating: 4.5,
    reviewsCount: 85,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '36',
    name: 'Lash Sensational Mascara',
    description: 'Mascara cils sensationnels',
    longDescription: 'Mascara cils sensationnels. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Lash Sensational Mascara Maybelline'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'Maybelline',
    rating: 4.6,
    reviewsCount: 86,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '37',
    name: 'The Falsies Mascara',
    description: 'Mascara volume faux cils',
    longDescription: 'Mascara volume faux cils. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('The Falsies Mascara Maybelline'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'Maybelline',
    rating: 4.7,
    reviewsCount: 87,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '38',
    name: 'Great Lash Mascara',
    description: 'Mascara grand cils',
    longDescription: 'Mascara grand cils. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Great Lash Mascara Maybelline'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'Maybelline',
    rating: 4.8,
    reviewsCount: 88,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '39',
    name: 'Fit Me! Foundation',
    description: 'Fond de teint ajusté',
    longDescription: 'Fond de teint ajusté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Fit Me! Foundation Maybelline'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Maybelline',
    rating: 4.9,
    reviewsCount: 89,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '40',
    name: 'Master Precise Liquid Eyeliner',
    description: 'Eyeliner liquide précis',
    longDescription: 'Eyeliner liquide précis. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Master Precise Liquid Eyeliner Maybelline'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Maybelline',
    rating: 4.0,
    reviewsCount: 90,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '41',
    name: 'Colorama Nail Polish',
    description: 'Vernis à ongles colorama',
    longDescription: 'Vernis à ongles colorama. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Colorama Nail Polish Maybelline'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Maybelline',
    rating: 4.1,
    reviewsCount: 91,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '42',
    name: 'Dream Satin Liquid Foundation',
    description: 'Fond de teint liquide satin',
    longDescription: 'Fond de teint liquide satin. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Dream Satin Liquid Foundation Maybelline'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Maybelline',
    rating: 4.2,
    reviewsCount: 92,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '43',
    name: 'Instant Age Rewind Concealer',
    description: 'Correcteur anti-âge',
    longDescription: 'Correcteur anti-âge. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Instant Age Rewind Concealer Maybelline'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Maybelline',
    rating: 4.3,
    reviewsCount: 93,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '44',
    name: 'Master Chrome Highlighter',
    description: 'Highlighter chrome',
    longDescription: 'Highlighter chrome. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Master Chrome Highlighter Maybelline'),
    category: 'maquillage',
    subCategory: 'Highlighter',
    brand: 'Maybelline',
    rating: 4.4,
    reviewsCount: 94,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '45',
    name: 'The Blushed Nudes Palette',
    description: 'Palette fards nude',
    longDescription: 'Palette fards nude. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('The Blushed Nudes Palette Maybelline'),
    category: 'maquillage',
    subCategory: 'Palettes',
    brand: 'Maybelline',
    rating: 4.5,
    reviewsCount: 95,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '46',
    name: 'The Nudes Palette',
    description: 'Palette nude',
    longDescription: 'Palette nude. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('The Nudes Palette Maybelline'),
    category: 'maquillage',
    subCategory: 'Palettes',
    brand: 'Maybelline',
    rating: 4.6,
    reviewsCount: 96,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '47',
    name: 'Color Riche Lipstick',
    description: 'Rouge à lèvres riche couleur',
    longDescription: 'Rouge à lèvres riche couleur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Color Riche Lipstick L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'L’Oréal Paris',
    rating: 4.7,
    reviewsCount: 97,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '48',
    name: 'Volume Million Lashes',
    description: 'Mascara million cils',
    longDescription: 'Mascara million cils. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Volume Million Lashes L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'L’Oréal Paris',
    rating: 4.8,
    reviewsCount: 98,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '49',
    name: 'Telescopic Mascara',
    description: 'Mascara télescopique',
    longDescription: 'Mascara télescopique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Telescopic Mascara L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'L’Oréal Paris',
    rating: 4.9,
    reviewsCount: 99,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '50',
    name: 'Liner Signature',
    description: 'Eyeliner signature',
    longDescription: 'Eyeliner signature. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Liner Signature L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.0,
    reviewsCount: 100,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '51',
    name: 'Blush Subtil',
    description: 'Blush subtil',
    longDescription: 'Blush subtil. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Blush Subtil L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.1,
    reviewsCount: 101,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '52',
    name: 'Glow Paradise',
    description: 'Baume à lèvres teinté',
    longDescription: 'Baume à lèvres teinté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Glow Paradise L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'L’Oréal Paris',
    rating: 4.2,
    reviewsCount: 102,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '53',
    name: 'Age Perfect Radiant Serum Foundation',
    description: 'Fond de teint sérum',
    longDescription: 'Fond de teint sérum. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.99,
    image: getProductImagePath('Age Perfect Radiant Serum Foundation L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.3,
    reviewsCount: 103,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '54',
    name: 'Infallible Pro-Matte Foundation',
    description: 'Fond de teint mat',
    longDescription: 'Fond de teint mat. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Infallible Pro-Matte Foundation L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.4,
    reviewsCount: 104,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '55',
    name: 'True Match Lumi Foundation',
    description: 'Fond de teint lumineux',
    longDescription: 'Fond de teint lumineux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('True Match Lumi Foundation L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.5,
    reviewsCount: 105,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '56',
    name: 'Infallible Pro-Last Lipstick',
    description: 'Rouge à lèvres longue tenue',
    longDescription: 'Rouge à lèvres longue tenue. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Infallible Pro-Last Lipstick L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'L’Oréal Paris',
    rating: 4.6,
    reviewsCount: 106,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '57',
    name: 'Color Riche Shine Lipstick',
    description: 'Rouge à lèvres brillant',
    longDescription: 'Rouge à lèvres brillant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Color Riche Shine Lipstick L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'L’Oréal Paris',
    rating: 4.7,
    reviewsCount: 107,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '58',
    name: 'Voluminous Lash Paradise Mascara',
    description: 'Mascara volume paradis',
    longDescription: 'Mascara volume paradis. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Voluminous Lash Paradise Mascara L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'L’Oréal Paris',
    rating: 4.8,
    reviewsCount: 108,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '59',
    name: 'Brow Stylist',
    description: 'Stylo sourcils',
    longDescription: 'Stylo sourcils. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Brow Stylist L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.9,
    reviewsCount: 109,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '60',
    name: 'Infallible Pro-Spray & Set',
    description: 'Fixateur maquillage',
    longDescription: 'Fixateur maquillage. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Infallible Pro-Spray & Set L’Oréal Paris'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'L’Oréal Paris',
    rating: 4.0,
    reviewsCount: 110,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  // SOINS CORPS
  {
    id: '61',
    name: 'The Ritual of Namaste Body Cream',
    description: 'Crème corps ayurvédique',
    longDescription: 'Crème corps ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Namaste Body Cream Rituals'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Rituals',
    rating: 4.1,
    reviewsCount: 111,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '62',
    name: 'The Ritual of Sakura Body Cream',
    description: 'Crème corps cerisier',
    longDescription: 'Crème corps cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.95,
    image: getProductImagePath('The Ritual of Sakura Body Cream Rituals'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Rituals',
    rating: 4.2,
    reviewsCount: 112,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '63',
    name: 'The Ritual of Karma Body Cream',
    description: 'Crème corps karma',
    longDescription: 'Crème corps karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 36.95,
    image: getProductImagePath('The Ritual of Karma Body Cream Rituals'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Rituals',
    rating: 4.3,
    reviewsCount: 113,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '64',
    name: 'The Ritual of Ayurveda Body Cream',
    description: 'Crème corps ayurvéda',
    longDescription: 'Crème corps ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 35.95,
    image: getProductImagePath('The Ritual of Ayurveda Body Cream Rituals'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Rituals',
    rating: 4.4,
    reviewsCount: 114,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '65',
    name: 'The Ritual of Hammam Body Scrub',
    description: 'Gommage corps hammam',
    longDescription: 'Gommage corps hammam. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 38.95,
    image: getProductImagePath('The Ritual of Hammam Body Scrub Rituals'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Rituals',
    rating: 4.5,
    reviewsCount: 115,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '66',
    name: 'The Ritual of Namaste Body Scrub',
    description: 'Gommage corps ayurvédique',
    longDescription: 'Gommage corps ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 36.95,
    image: getProductImagePath('The Ritual of Namaste Body Scrub Rituals'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Rituals',
    rating: 4.6,
    reviewsCount: 116,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '67',
    name: 'The Ritual of Sakura Body Scrub',
    description: 'Gommage corps cerisier',
    longDescription: 'Gommage corps cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Sakura Body Scrub Rituals'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Rituals',
    rating: 4.7,
    reviewsCount: 117,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '68',
    name: 'The Ritual of Karma Body Scrub',
    description: 'Gommage corps karma',
    longDescription: 'Gommage corps karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 37.95,
    image: getProductImagePath('The Ritual of Karma Body Scrub Rituals'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Rituals',
    rating: 4.8,
    reviewsCount: 118,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '69',
    name: 'The Ritual of Ayurveda Body Scrub',
    description: 'Gommage corps ayurvéda',
    longDescription: 'Gommage corps ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 35.95,
    image: getProductImagePath('The Ritual of Ayurveda Body Scrub Rituals'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Rituals',
    rating: 4.9,
    reviewsCount: 119,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '70',
    name: 'The Ritual of Namaste Body Oil',
    description: 'Huile corps ayurvédique',
    longDescription: 'Huile corps ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 39.95,
    image: getProductImagePath('The Ritual of Namaste Body Oil Rituals'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Rituals',
    rating: 4.0,
    reviewsCount: 120,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '71',
    name: 'The Ritual of Sakura Body Oil',
    description: 'Huile corps cerisier',
    longDescription: 'Huile corps cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 37.95,
    image: getProductImagePath('The Ritual of Sakura Body Oil Rituals'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Rituals',
    rating: 4.1,
    reviewsCount: 121,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '72',
    name: 'The Ritual of Karma Body Oil',
    description: 'Huile corps karma',
    longDescription: 'Huile corps karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 41.95,
    image: getProductImagePath('The Ritual of Karma Body Oil Rituals'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Rituals',
    rating: 4.2,
    reviewsCount: 122,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '73',
    name: 'The Ritual of Ayurveda Body Oil',
    description: 'Huile corps ayurvéda',
    longDescription: 'Huile corps ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 38.95,
    image: getProductImagePath('The Ritual of Ayurveda Body Oil Rituals'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Rituals',
    rating: 4.3,
    reviewsCount: 123,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '74',
    name: 'The Ritual of Hammam Body Oil',
    description: 'Huile corps hammam',
    longDescription: 'Huile corps hammam. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 40.95,
    image: getProductImagePath('The Ritual of Hammam Body Oil Rituals'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Rituals',
    rating: 4.4,
    reviewsCount: 124,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '75',
    name: 'Nivea Body Lotion',
    description: 'Lotion corps hydratante',
    longDescription: 'Lotion corps hydratante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Nivea Body Lotion Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.5,
    reviewsCount: 125,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '76',
    name: 'Nivea Rich Nourishing Body Lotion',
    description: 'Lotion corps nourrissante',
    longDescription: 'Lotion corps nourrissante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Nivea Rich Nourishing Body Lotion Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.6,
    reviewsCount: 126,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '77',
    name: 'Nivea Soft Moisturising Cream',
    description: 'Crème corps douce',
    longDescription: 'Crème corps douce. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Nivea Soft Moisturising Cream Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.7,
    reviewsCount: 127,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '78',
    name: 'Nivea Q10 Plus Firming Body Lotion',
    description: 'Lotion corps fermeté',
    longDescription: 'Lotion corps fermeté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Nivea Q10 Plus Firming Body Lotion Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.8,
    reviewsCount: 128,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '79',
    name: 'Nivea Sun Protect & Moisture',
    description: 'Crème solaire hydratante',
    longDescription: 'Crème solaire hydratante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Nivea Sun Protect & Moisture Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.9,
    reviewsCount: 129,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '80',
    name: 'Nivea Sun Protect & Refresh',
    description: 'Spray solaire rafraîchissant',
    longDescription: 'Spray solaire rafraîchissant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Nivea Sun Protect & Refresh Nivea'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Nivea',
    rating: 4.0,
    reviewsCount: 130,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '81',
    name: 'Garnier Body Intensive 7 Days',
    description: 'Lotion corps 7 jours',
    longDescription: 'Lotion corps 7 jours. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Garnier Body Intensive 7 Days Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.1,
    reviewsCount: 131,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '82',
    name: 'Garnier Body Intensive Repair',
    description: 'Lotion corps réparatrice',
    longDescription: 'Lotion corps réparatrice. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Garnier Body Intensive Repair Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.2,
    reviewsCount: 132,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '83',
    name: 'Garnier Body Intensive Nourishing',
    description: 'Lotion corps nourrissante',
    longDescription: 'Lotion corps nourrissante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Garnier Body Intensive Nourishing Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.3,
    reviewsCount: 133,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '84',
    name: 'Garnier Body Intensive Smoothing',
    description: 'Lotion corps lissante',
    longDescription: 'Lotion corps lissante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Garnier Body Intensive Smoothing Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.4,
    reviewsCount: 134,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '85',
    name: 'Garnier Body Intensive Firming',
    description: 'Lotion corps fermeté',
    longDescription: 'Lotion corps fermeté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Garnier Body Intensive Firming Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.5,
    reviewsCount: 135,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '86',
    name: 'Garnier Body Intensive Anti-Age',
    description: 'Lotion corps anti-âge',
    longDescription: 'Lotion corps anti-âge. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Garnier Body Intensive Anti-Age Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.6,
    reviewsCount: 136,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '87',
    name: 'Garnier Body Intensive Sun Protection',
    description: 'Protection solaire corps',
    longDescription: 'Protection solaire corps. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Garnier Body Intensive Sun Protection Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.7,
    reviewsCount: 137,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '88',
    name: 'Garnier Body Intensive After Sun',
    description: 'Après-soleil apaisant',
    longDescription: 'Après-soleil apaisant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Garnier Body Intensive After Sun Garnier'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Garnier',
    rating: 4.8,
    reviewsCount: 138,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '89',
    name: 'Garnier Body Intensive Exfoliating',
    description: 'Gommage corps exfoliant',
    longDescription: 'Gommage corps exfoliant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Garnier Body Intensive Exfoliating Garnier'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Garnier',
    rating: 4.9,
    reviewsCount: 139,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '90',
    name: 'Garnier Body Intensive Hand Cream',
    description: 'Crème mains intensive',
    longDescription: 'Crème mains intensive. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Garnier Body Intensive Hand Cream Garnier'),
    category: 'soins-corps',
    subCategory: 'Soins des mains',
    brand: 'Garnier',
    rating: 4.0,
    reviewsCount: 140,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  // CHEVEUX
  {
    id: '91',
    name: 'Elvive Total Repair 5',
    description: 'Shampoing réparateur 5 actions',
    longDescription: 'Shampoing réparateur 5 actions. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Elvive Total Repair 5 L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.1,
    reviewsCount: 141,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '92',
    name: 'Elvive Dream Lengths',
    description: 'Shampoing longueur rêve',
    longDescription: 'Shampoing longueur rêve. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Elvive Dream Lengths L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.2,
    reviewsCount: 142,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '93',
    name: 'Elvive Extraordinary Oil',
    description: 'Huile capillaire extraordinaire',
    longDescription: 'Huile capillaire extraordinaire. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Elvive Extraordinary Oil L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Soins coiffants',
    brand: 'L’Oréal Paris',
    rating: 4.3,
    reviewsCount: 143,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '94',
    name: 'Elvive Color Vibrancy',
    description: 'Shampoing cheveux colorés',
    longDescription: 'Shampoing cheveux colorés. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Elvive Color Vibrancy L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.4,
    reviewsCount: 144,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '95',
    name: 'Elvive Volume Filler',
    description: 'Shampoing volume',
    longDescription: 'Shampoing volume. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Elvive Volume Filler L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.5,
    reviewsCount: 145,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '96',
    name: 'Elvive Smooth Intense',
    description: 'Shampoing lissant intense',
    longDescription: 'Shampoing lissant intense. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Elvive Smooth Intense L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.6,
    reviewsCount: 146,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '97',
    name: 'Elvive Nutri-Gloss',
    description: 'Shampoing brillance nutritif',
    longDescription: 'Shampoing brillance nutritif. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Elvive Nutri-Gloss L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.7,
    reviewsCount: 147,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '98',
    name: 'Elvive Fibrology',
    description: 'Shampoing densité',
    longDescription: 'Shampoing densité. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Elvive Fibrology L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.8,
    reviewsCount: 148,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '99',
    name: 'Elvive Hyaluron Plump',
    description: 'Shampoing hydratant hyaluron',
    longDescription: 'Shampoing hydratant hyaluron. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 27.99,
    image: getProductImagePath('Elvive Hyaluron Plump L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'L’Oréal Paris',
    rating: 4.9,
    reviewsCount: 149,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '100',
    name: 'Elvive Wonder Water',
    description: 'Traitement capillaire eau',
    longDescription: 'Traitement capillaire eau. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 30.99,
    image: getProductImagePath('Elvive Wonder Water L’Oréal Paris'),
    category: 'cheveux',
    subCategory: 'Masques',
    brand: 'L’Oréal Paris',
    rating: 4.0,
    reviewsCount: 150,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '101',
    name: 'Ultra Doux Shampoo',
    description: 'Shampoing ultra doux',
    longDescription: 'Shampoing ultra doux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Ultra Doux Shampoo Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.1,
    reviewsCount: 151,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '102',
    name: 'Ultra Doux Conditioner',
    description: 'Après-shampoing ultra doux',
    longDescription: 'Après-shampoing ultra doux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Ultra Doux Conditioner Garnier'),
    category: 'cheveux',
    subCategory: 'Après-shampoings',
    brand: 'Garnier',
    rating: 4.2,
    reviewsCount: 152,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '103',
    name: 'Ultra Doux Hair Mask',
    description: 'Masque capillaire ultra doux',
    longDescription: 'Masque capillaire ultra doux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Ultra Doux Hair Mask Garnier'),
    category: 'cheveux',
    subCategory: 'Masques',
    brand: 'Garnier',
    rating: 4.3,
    reviewsCount: 153,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '104',
    name: 'Ultra Doux Oil',
    description: 'Huile capillaire ultra doux',
    longDescription: 'Huile capillaire ultra doux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Ultra Doux Oil Garnier'),
    category: 'cheveux',
    subCategory: 'Soins coiffants',
    brand: 'Garnier',
    rating: 4.4,
    reviewsCount: 154,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '105',
    name: 'Fructis Strength & Shine',
    description: 'Shampoing force brillance',
    longDescription: 'Shampoing force brillance. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Fructis Strength & Shine Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.5,
    reviewsCount: 155,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '106',
    name: 'Fructis Smooth & Shine',
    description: 'Shampoing lissant brillance',
    longDescription: 'Shampoing lissant brillance. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Fructis Smooth & Shine Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.6,
    reviewsCount: 156,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '107',
    name: 'Fructis Volume & Body',
    description: 'Shampoing volume',
    longDescription: 'Shampoing volume. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Fructis Volume & Body Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.7,
    reviewsCount: 157,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '108',
    name: 'Fructis Color Shield',
    description: 'Shampoing protection couleur',
    longDescription: 'Shampoing protection couleur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Fructis Color Shield Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.8,
    reviewsCount: 158,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '109',
    name: 'Fructis Repair & Shine',
    description: 'Shampoing réparation brillance',
    longDescription: 'Shampoing réparation brillance. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Fructis Repair & Shine Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.9,
    reviewsCount: 159,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '110',
    name: 'Fructis Hydrating',
    description: 'Shampoing hydratant',
    longDescription: 'Shampoing hydratant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Fructis Hydrating Garnier'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Garnier',
    rating: 4.0,
    reviewsCount: 160,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '111',
    name: 'Nivea Hair Care Shampoo',
    description: 'Shampoing soin cheveux',
    longDescription: 'Shampoing soin cheveux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Nivea Hair Care Shampoo Nivea'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Nivea',
    rating: 4.1,
    reviewsCount: 161,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '112',
    name: 'Nivea Hair Care Conditioner',
    description: 'Après-shampoing soin',
    longDescription: 'Après-shampoing soin. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Nivea Hair Care Conditioner Nivea'),
    category: 'cheveux',
    subCategory: 'Après-shampoings',
    brand: 'Nivea',
    rating: 4.2,
    reviewsCount: 162,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '113',
    name: 'Nivea Hair Care Hair Mask',
    description: 'Masque capillaire soin',
    longDescription: 'Masque capillaire soin. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Nivea Hair Care Hair Mask Nivea'),
    category: 'cheveux',
    subCategory: 'Masques',
    brand: 'Nivea',
    rating: 4.3,
    reviewsCount: 163,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '114',
    name: 'Nivea Hair Care Oil',
    description: 'Huile capillaire soin',
    longDescription: 'Huile capillaire soin. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Nivea Hair Care Oil Nivea'),
    category: 'cheveux',
    subCategory: 'Soins coiffants',
    brand: 'Nivea',
    rating: 4.4,
    reviewsCount: 164,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '115',
    name: 'The Ritual of Namaste Shampoo',
    description: 'Shampoing ayurvédique',
    longDescription: 'Shampoing ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Namaste Shampoo Rituals'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Rituals',
    rating: 4.5,
    reviewsCount: 165,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '116',
    name: 'The Ritual of Sakura Shampoo',
    description: 'Shampoing cerisier',
    longDescription: 'Shampoing cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.95,
    image: getProductImagePath('The Ritual of Sakura Shampoo Rituals'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Rituals',
    rating: 4.6,
    reviewsCount: 166,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '117',
    name: 'The Ritual of Karma Shampoo',
    description: 'Shampoing karma',
    longDescription: 'Shampoing karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 36.95,
    image: getProductImagePath('The Ritual of Karma Shampoo Rituals'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Rituals',
    rating: 4.7,
    reviewsCount: 167,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '118',
    name: 'The Ritual of Ayurveda Shampoo',
    description: 'Shampoing ayurvéda',
    longDescription: 'Shampoing ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 35.95,
    image: getProductImagePath('The Ritual of Ayurveda Shampoo Rituals'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Rituals',
    rating: 4.8,
    reviewsCount: 168,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '119',
    name: 'The Ritual of Hammam Shampoo',
    description: 'Shampoing hammam',
    longDescription: 'Shampoing hammam. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 37.95,
    image: getProductImagePath('The Ritual of Hammam Shampoo Rituals'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Rituals',
    rating: 4.9,
    reviewsCount: 169,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '120',
    name: 'The Ritual of Namaste Conditioner',
    description: 'Après-shampoing ayurvédique',
    longDescription: 'Après-shampoing ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Namaste Conditioner Rituals'),
    category: 'cheveux',
    subCategory: 'Après-shampoings',
    brand: 'Rituals',
    rating: 4.0,
    reviewsCount: 170,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  // PARFUMS
  {
    id: '121',
    name: 'The Ritual of Namaste Eau de Parfum',
    description: 'Parfum ayurvédique',
    longDescription: 'Parfum ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 49.95,
    image: getProductImagePath('The Ritual of Namaste Eau de Parfum Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.1,
    reviewsCount: 171,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '122',
    name: 'The Ritual of Sakura Eau de Parfum',
    description: 'Parfum cerisier',
    longDescription: 'Parfum cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 47.95,
    image: getProductImagePath('The Ritual of Sakura Eau de Parfum Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.2,
    reviewsCount: 172,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '123',
    name: 'The Ritual of Karma Eau de Parfum',
    description: 'Parfum karma',
    longDescription: 'Parfum karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 51.95,
    image: getProductImagePath('The Ritual of Karma Eau de Parfum Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.3,
    reviewsCount: 173,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '124',
    name: 'The Ritual of Ayurveda Eau de Parfum',
    description: 'Parfum ayurvéda',
    longDescription: 'Parfum ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 49.95,
    image: getProductImagePath('The Ritual of Ayurveda Eau de Parfum Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.4,
    reviewsCount: 174,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '125',
    name: 'The Ritual of Hammam Eau de Parfum',
    description: 'Parfum hammam',
    longDescription: 'Parfum hammam. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 50.95,
    image: getProductImagePath('The Ritual of Hammam Eau de Parfum Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.5,
    reviewsCount: 175,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '126',
    name: 'The Ritual of Namaste Body Mist',
    description: 'Brume parfumée ayurvédique',
    longDescription: 'Brume parfumée ayurvédique. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.95,
    image: getProductImagePath('The Ritual of Namaste Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.6,
    reviewsCount: 176,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '127',
    name: 'The Ritual of Sakura Body Mist',
    description: 'Brume parfumée cerisier',
    longDescription: 'Brume parfumée cerisier. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.95,
    image: getProductImagePath('The Ritual of Sakura Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.7,
    reviewsCount: 177,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '128',
    name: 'The Ritual of Karma Body Mist',
    description: 'Brume parfumée karma',
    longDescription: 'Brume parfumée karma. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 36.95,
    image: getProductImagePath('The Ritual of Karma Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.8,
    reviewsCount: 178,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '129',
    name: 'The Ritual of Ayurveda Body Mist',
    description: 'Brume parfumée ayurvéda',
    longDescription: 'Brume parfumée ayurvéda. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 35.95,
    image: getProductImagePath('The Ritual of Ayurveda Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.9,
    reviewsCount: 179,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '130',
    name: 'The Ritual of Hammam Body Mist',
    description: 'Brume parfumée hammam',
    longDescription: 'Brume parfumée hammam. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 37.95,
    image: getProductImagePath('The Ritual of Hammam Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.0,
    reviewsCount: 180,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '131',
    name: 'Nivea Deodorant',
    description: 'Déodorant protection',
    longDescription: 'Déodorant protection. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Nivea Deodorant Nivea'),
    category: 'parfums',
    subCategory: '',
    brand: 'Nivea',
    rating: 4.1,
    reviewsCount: 181,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '132',
    name: 'Nivea Roll-On',
    description: 'Déodorant roll-on',
    longDescription: 'Déodorant roll-on. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Nivea Roll-On Nivea'),
    category: 'parfums',
    subCategory: '',
    brand: 'Nivea',
    rating: 4.2,
    reviewsCount: 182,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '133',
    name: 'Nivea Spray',
    description: 'Déodorant spray',
    longDescription: 'Déodorant spray. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Nivea Spray Nivea'),
    category: 'parfums',
    subCategory: '',
    brand: 'Nivea',
    rating: 4.3,
    reviewsCount: 183,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '134',
    name: 'Garnier Deodorant',
    description: 'Déodorant fraîcheur',
    longDescription: 'Déodorant fraîcheur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Garnier Deodorant Garnier'),
    category: 'parfums',
    subCategory: '',
    brand: 'Garnier',
    rating: 4.4,
    reviewsCount: 184,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '135',
    name: 'Garnier Roll-On',
    description: 'Déodorant roll-on',
    longDescription: 'Déodorant roll-on. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Garnier Roll-On Garnier'),
    category: 'parfums',
    subCategory: '',
    brand: 'Garnier',
    rating: 4.5,
    reviewsCount: 185,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '136',
    name: 'Garnier Spray',
    description: 'Déodorant spray',
    longDescription: 'Déodorant spray. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Garnier Spray Garnier'),
    category: 'parfums',
    subCategory: '',
    brand: 'Garnier',
    rating: 4.6,
    reviewsCount: 186,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '137',
    name: 'L’Oréal Paris Deodorant',
    description: 'Déodorant protection',
    longDescription: 'Déodorant protection. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('L’Oréal Paris Deodorant L’Oréal Paris'),
    category: 'parfums',
    subCategory: '',
    brand: 'L’Oréal Paris',
    rating: 4.7,
    reviewsCount: 187,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '138',
    name: 'L’Oréal Paris Roll-On',
    description: 'Déodorant roll-on',
    longDescription: 'Déodorant roll-on. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('L’Oréal Paris Roll-On L’Oréal Paris'),
    category: 'parfums',
    subCategory: '',
    brand: 'L’Oréal Paris',
    rating: 4.8,
    reviewsCount: 188,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '139',
    name: 'L’Oréal Paris Spray',
    description: 'Déodorant spray',
    longDescription: 'Déodorant spray. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('L’Oréal Paris Spray L’Oréal Paris'),
    category: 'parfums',
    subCategory: '',
    brand: 'L’Oréal Paris',
    rating: 4.9,
    reviewsCount: 189,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '140',
    name: 'Maybelline Deodorant',
    description: 'Déodorant fraîcheur',
    longDescription: 'Déodorant fraîcheur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Maybelline Deodorant Maybelline'),
    category: 'parfums',
    subCategory: '',
    brand: 'Maybelline',
    rating: 4.0,
    reviewsCount: 190,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '141',
    name: 'Maybelline Roll-On',
    description: 'Déodorant roll-on',
    longDescription: 'Déodorant roll-on. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Maybelline Roll-On Maybelline'),
    category: 'parfums',
    subCategory: '',
    brand: 'Maybelline',
    rating: 4.1,
    reviewsCount: 191,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '142',
    name: 'Maybelline Spray',
    description: 'Déodorant spray',
    longDescription: 'Déodorant spray. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Maybelline Spray Maybelline'),
    category: 'parfums',
    subCategory: '',
    brand: 'Maybelline',
    rating: 4.2,
    reviewsCount: 192,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '143',
    name: 'The Ordinary Deodorant',
    description: 'Déodorant naturel',
    longDescription: 'Déodorant naturel. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.9,
    image: getProductImagePath('The Ordinary Deodorant The Ordinary'),
    category: 'parfums',
    subCategory: '',
    brand: 'The Ordinary',
    rating: 4.3,
    reviewsCount: 193,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '144',
    name: 'The Inkey List Deodorant',
    description: 'Déodorant pur',
    longDescription: 'Déodorant pur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.9,
    image: getProductImagePath('The Inkey List Deodorant The Inkey List'),
    category: 'parfums',
    subCategory: '',
    brand: 'The Inkey List',
    rating: 4.4,
    reviewsCount: 194,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '145',
    name: 'Rituals Deodorant',
    description: 'Déodorant rituel',
    longDescription: 'Déodorant rituel. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.95,
    image: getProductImagePath('Rituals Deodorant Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.5,
    reviewsCount: 195,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '146',
    name: 'Rituals Roll-On',
    description: 'Déodorant roll-on',
    longDescription: 'Déodorant roll-on. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.95,
    image: getProductImagePath('Rituals Roll-On Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.6,
    reviewsCount: 196,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '147',
    name: 'Rituals Spray',
    description: 'Déodorant spray',
    longDescription: 'Déodorant spray. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 30.95,
    image: getProductImagePath('Rituals Spray Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.7,
    reviewsCount: 197,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '148',
    name: 'Rituals Body Mist',
    description: 'Brume parfumée',
    longDescription: 'Brume parfumée. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 32.95,
    image: getProductImagePath('Rituals Body Mist Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.8,
    reviewsCount: 198,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '149',
    name: 'Rituals Eau de Toilette',
    description: 'Eau de toilette',
    longDescription: 'Eau de toilette. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 44.95,
    image: getProductImagePath('Rituals Eau de Toilette Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.9,
    reviewsCount: 199,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '150',
    name: 'Rituals Eau de Cologne',
    description: 'Eau de cologne',
    longDescription: 'Eau de cologne. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 42.95,
    image: getProductImagePath('Rituals Eau de Cologne Rituals'),
    category: 'parfums',
    subCategory: '',
    brand: 'Rituals',
    rating: 4.0,
    reviewsCount: 200,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  // ACCESSOIRES
  {
    id: '151',
    name: 'Makeup Brush Set',
    description: 'Set pinceaux maquillage',
    longDescription: 'Set pinceaux maquillage. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.99,
    image: getProductImagePath('Makeup Brush Set Real Techniques'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Real Techniques',
    rating: 4.1,
    reviewsCount: 201,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '152',
    name: 'Beauty Sponge',
    description: 'Éponge beauté',
    longDescription: 'Éponge beauté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Beauty Sponge Real Techniques'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Real Techniques',
    rating: 4.2,
    reviewsCount: 202,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '153',
    name: 'Makeup Mirror LED',
    description: 'Miroir maquillage LED',
    longDescription: 'Miroir maquillage LED. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 89.99,
    image: getProductImagePath('Makeup Mirror LED Simplehuman'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Simplehuman',
    rating: 4.3,
    reviewsCount: 203,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '154',
    name: 'Brush Holder',
    description: 'Porte-pinceaux',
    longDescription: 'Porte-pinceaux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Brush Holder Real Techniques'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Real Techniques',
    rating: 4.4,
    reviewsCount: 204,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '155',
    name: 'Makeup Organizer',
    description: 'Organisateur maquillage',
    longDescription: 'Organisateur maquillage. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 49.99,
    image: getProductImagePath('Makeup Organizer Simplehuman'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Simplehuman',
    rating: 4.5,
    reviewsCount: 205,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '156',
    name: 'Makeup Bag',
    description: 'Trousse maquillage',
    longDescription: 'Trousse maquillage. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Makeup Bag Real Techniques'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Real Techniques',
    rating: 4.6,
    reviewsCount: 206,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '157',
    name: 'Brush Cleaner',
    description: 'Nettoyant pinceaux',
    longDescription: 'Nettoyant pinceaux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Brush Cleaner Real Techniques'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Real Techniques',
    rating: 4.7,
    reviewsCount: 207,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '158',
    name: 'Makeup Remover Cloths',
    description: 'Lingettes démaquillantes',
    longDescription: 'Lingettes démaquillantes. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Makeup Remover Cloths Real Techniques'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Real Techniques',
    rating: 4.8,
    reviewsCount: 208,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '159',
    name: 'Eyelash Curler',
    description: 'Recourbe-cils',
    longDescription: 'Recourbe-cils. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Eyelash Curler Tweezerman'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Tweezerman',
    rating: 4.9,
    reviewsCount: 209,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '160',
    name: 'Tweezers',
    description: 'Pince à épiler',
    longDescription: 'Pince à épiler. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Tweezers Tweezerman'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Tweezerman',
    rating: 4.0,
    reviewsCount: 210,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '161',
    name: 'Nail Clipper Set',
    description: 'Coupe-ongles',
    longDescription: 'Coupe-ongles. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Nail Clipper Set Tweezerman'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Tweezerman',
    rating: 4.1,
    reviewsCount: 211,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '162',
    name: 'Hair Brush',
    description: 'Brosse cheveux',
    longDescription: 'Brosse cheveux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 25.99,
    image: getProductImagePath('Hair Brush Tangle Teezer'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Tangle Teezer',
    rating: 4.2,
    reviewsCount: 212,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '163',
    name: 'Detangling Brush',
    description: 'Brosse démêlante',
    longDescription: 'Brosse démêlante. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 26.99,
    image: getProductImagePath('Detangling Brush Tangle Teezer'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Tangle Teezer',
    rating: 4.3,
    reviewsCount: 213,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '164',
    name: 'Hair Dryer',
    description: 'Sèche-cheveux',
    longDescription: 'Sèche-cheveux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 89.99,
    image: getProductImagePath('Hair Dryer Remington'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Remington',
    rating: 4.4,
    reviewsCount: 214,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '165',
    name: 'Straightening Iron',
    description: 'Lisseur',
    longDescription: 'Lisseur. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 79.99,
    image: getProductImagePath('Straightening Iron Remington'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Remington',
    rating: 4.5,
    reviewsCount: 215,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '166',
    name: 'Curling Iron',
    description: 'Fer à boucler',
    longDescription: 'Fer à boucler. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 69.99,
    image: getProductImagePath('Curling Iron Remington'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Remington',
    rating: 4.6,
    reviewsCount: 216,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '167',
    name: 'Hair Clips',
    description: 'Pinces à cheveux',
    longDescription: 'Pinces à cheveux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 21.99,
    image: getProductImagePath('Hair Clips Goody'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Goody',
    rating: 4.7,
    reviewsCount: 217,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '168',
    name: 'Hair Ties',
    description: 'Élastiques cheveux',
    longDescription: 'Élastiques cheveux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 22.99,
    image: getProductImagePath('Hair Ties Goody'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Goody',
    rating: 4.8,
    reviewsCount: 218,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '169',
    name: 'Hair Scrunchie',
    description: 'Chouchou',
    longDescription: 'Chouchou. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 23.99,
    image: getProductImagePath('Hair Scrunchie Goody'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Goody',
    rating: 4.9,
    reviewsCount: 219,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '170',
    name: 'Hair Band',
    description: 'Bandeau cheveux',
    longDescription: 'Bandeau cheveux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Hair Band Goody'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Goody',
    rating: 4.0,
    reviewsCount: 220,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '171',
    name: 'Makeup Palette',
    description: 'Palette maquillage',
    longDescription: 'Palette maquillage. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 34.99,
    image: getProductImagePath('Makeup Palette Z Palette'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Z Palette',
    rating: 4.1,
    reviewsCount: 221,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '172',
    name: 'Brush Set Pro',
    description: 'Set pinceaux pro',
    longDescription: 'Set pinceaux pro. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 89.99,
    image: getProductImagePath('Brush Set Pro Zoeva'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Zoeva',
    rating: 4.2,
    reviewsCount: 222,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '173',
    name: 'Beauty Blender',
    description: 'Éponge beauté',
    longDescription: 'Éponge beauté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 28.99,
    image: getProductImagePath('Beauty Blender Beautyblender'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Beautyblender',
    rating: 4.3,
    reviewsCount: 223,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '174',
    name: 'Makeup Sponge Set',
    description: 'Set éponges',
    longDescription: 'Set éponges. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 49.99,
    image: getProductImagePath('Makeup Sponge Set Beautyblender'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Beautyblender',
    rating: 4.4,
    reviewsCount: 224,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '175',
    name: 'Brush Cleaner Mat',
    description: 'Tapis nettoyant',
    longDescription: 'Tapis nettoyant. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Brush Cleaner Mat Sigma'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Sigma',
    rating: 4.5,
    reviewsCount: 225,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '176',
    name: 'Makeup Brush Set',
    description: 'Set pinceaux',
    longDescription: 'Set pinceaux. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 79.99,
    image: getProductImagePath('Makeup Brush Set Sigma'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Sigma',
    rating: 4.6,
    reviewsCount: 226,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '177',
    name: 'Beauty Sponge',
    description: 'Éponge beauté',
    longDescription: 'Éponge beauté. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 24.99,
    image: getProductImagePath('Beauty Sponge Sigma'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Sigma',
    rating: 4.7,
    reviewsCount: 227,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '178',
    name: 'Makeup Mirror',
    description: 'Miroir maquillage',
    longDescription: 'Miroir maquillage. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 59.99,
    image: getProductImagePath('Makeup Mirror Conair'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Conair',
    rating: 4.8,
    reviewsCount: 228,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '179',
    name: 'LED Mirror',
    description: 'Miroir LED',
    longDescription: 'Miroir LED. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 69.99,
    image: getProductImagePath('LED Mirror Conair'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Conair',
    rating: 4.9,
    reviewsCount: 229,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
  {
    id: '180',
    name: 'Travel Mirror',
    description: 'Miroir voyage',
    longDescription: 'Miroir voyage. Produit de qualité professionnelle disponible aux Pays-Bas.',
    price: 29.99,
    image: getProductImagePath('Travel Mirror Conair'),
    category: 'accessoires',
    subCategory: '',
    brand: 'Conair',
    rating: 4.0,
    reviewsCount: 230,
    inStock: true,
    isBestSeller: false,
    badges: []
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    productId: '1',
    userName: 'Sophie M.',
    rating: 5,
    comment: 'Excellent produit ! Ma peau est visiblement plus radieuse après seulement 2 semaines d’utilisation.',
    date: '2024-01-15',
    verified: true
  },
  {
    id: '2',
    productId: '1',
    userName: 'Emma L.',
    rating: 5,
    comment: 'Je recommande vivement ce sérum. Texture agréable et résultats impressionnants.',
    date: '2024-01-10',
    verified: true
  },
  {
    id: '3',
    productId: '24',
    userName: 'Léa D.',
    rating: 5,
    comment: 'Ma couleur préférée ! Tenue exceptionnelle et texture très confortable.',
    date: '2024-01-20',
    verified: true
  },
  {
    id: '4',
    productId: '20',
    userName: 'Camille R.',
    rating: 5,
    comment: 'Fond de teint parfait ! Couvrance excellente et tenue toute la journée.',
    date: '2024-01-22',
    verified: true
  },
  {
    id: '5',
    productId: '37',
    userName: 'Marie K.',
    rating: 5,
    comment: 'Lotion super hydratante, ma peau est douce comme la soie !',
    date: '2024-01-18',
    verified: true
  },
];

