import { Product, Category, Review } from '@/types';

/**
 * Convertit un nom de produit en nom de fichier image
 */
function productNameToImageName(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '_')
    .replace(/[^a-z0-9_àáâãäåèéêëìíîïòóôõöùúûüýÿç]/gi, '')
    .replace(/_{2,}/g, '_')
    .replace(/^_|_$/g, '') + '.jpg';
}

/**
 * Génère le chemin vers l'image d'un produit
 */
function getProductImagePath(productName: string): string {
  return `/image-products/${productNameToImageName(productName)}`;
}

export const categories: Category[] = [
  {
    id: '1',
    name: 'Soins du visage',
    slug: 'soins-visage',
    description: 'Crèmes, sérums, masques et produits de soin pour votre visage',
    image: getProductImagePath('Soins du visage'),
    subCategories: ['Crèmes hydratantes', 'Sérums', 'Masques', 'Nettoyants', 'Protection solaire']
  },
  {
    id: '2',
    name: 'Maquillage',
    slug: 'maquillage',
    description: 'Produits de maquillage pour sublimer votre beauté naturelle',
    image: getProductImagePath('Maquillage'),
    subCategories: ['Fond de teint', 'Rouge à lèvres', 'Mascara', 'Palettes', 'Highlighter']
  },
  {
    id: '3',
    name: 'Soins du corps',
    slug: 'soins-corps',
    description: 'Lotions, huiles et soins pour un corps radieux',
    image: getProductImagePath('Soins du corps'),
    subCategories: ['Lotions hydratantes', 'Huiles', 'Gommages', 'Soins des mains']
  },
  {
    id: '4',
    name: 'Cheveux',
    slug: 'cheveux',
    description: 'Shampoings, après-shampoings et soins capillaires',
    image: getProductImagePath('Cheveux'),
    subCategories: ['Shampoings', 'Après-shampoings', 'Masques', 'Soins coiffants']
  },
  {
    id: '5',
    name: 'Parfums',
    slug: 'parfums',
    description: 'Fragrances élégantes et raffinées',
    image: getProductImagePath('Parfums')
  },
  {
    id: '6',
    name: 'Accessoires beauté',
    slug: 'accessoires',
    description: 'Pinceaux, éponges et outils de beauté',
    image: getProductImagePath('Fond de Teint Fluide Mat')
  },
];

export const products: Product[] = [
  // SOINS DU VISAGE - Sérums
  {
    id: '1',
    name: 'Sérum Anti-Âge Premium',
    description: 'Sérum régénérant aux actifs naturels',
    longDescription: 'Notre sérum anti-âge premium est formulé avec des peptides et des antioxydants puissants pour réduire visiblement les signes de l\'âge. Enrichi en vitamine C et acide hyaluronique, il hydrate intensément et illumine votre teint.',
    price: 89.99,
    originalPrice: 119.99,
    image: getProductImagePath('Sérum Anti-Âge Premium'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'Essence Féminine',
    ingredients: 'Eau, Acide hyaluronique, Vitamine C, Peptides, Extrait de pépins de raisin',
    usage: 'Appliquez matin et soir sur un visage propre. Massez délicatement jusqu\'à pénétration complète.',
    skinType: ['Tous types', 'Peau mature'],
    rating: 4.8,
    reviewsCount: 124,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller', 'Natural']
  },
  {
    id: '2',
    name: 'Sérum Vitamine C Éclat',
    description: 'Éclat immédiat et protection anti-âge',
    longDescription: 'Sérum à la vitamine C pure qui illumine instantanément le teint et réduit les taches pigmentaires. Formule légère et non grasse, parfaite pour tous les types de peau.',
    price: 69.99,
    image: getProductImagePath('Sérum Vitamine C Éclat'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 156,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '3',
    name: 'Sérum Acide Hyaluronique Intense',
    description: 'Hydratation maximale pour une peau rebondie',
    longDescription: 'Sérum concentré en acide hyaluronique à différents poids moléculaires pour une hydratation profonde et durable. Redonne volume et élasticité à la peau.',
    price: 54.99,
    image: getProductImagePath('Sérum Acide Hyaluronique Intense'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'Essence Féminine',
    rating: 4.9,
    reviewsCount: 203,
    inStock: true
  },
  {
    id: '4',
    name: 'Sérum Rétinol Nuit',
    description: 'Correction des rides pendant la nuit',
    longDescription: 'Sérum au rétinol pur pour corriger les signes de l\'âge pendant votre sommeil. Texture douce, tolérance maximale grâce à la technologie encapsulée.',
    price: 79.99,
    originalPrice: 99.99,
    image: getProductImagePath('Sérum Rétinol Nuit'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 98,
    inStock: true
  },
  {
    id: '5',
    name: 'Sérum Niacinamide Pores',
    description: 'Minimise les pores et matifie la peau',
    longDescription: 'Sérum à la niacinamide pour réduire l\'apparence des pores, contrôler le sébum et unifier le teint. Idéal pour les peaux mixtes à grasses.',
    price: 49.99,
    image: getProductImagePath('Sérum Niacinamide Pores'),
    category: 'soins-visage',
    subCategory: 'Sérums',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 187,
    inStock: true
  },
  
  // SOINS DU VISAGE - Crèmes
  {
    id: '6',
    name: 'Crème Hydratante Intense',
    description: 'Hydratation 24h pour une peau éclatante',
    longDescription: 'Cette crème hydratante riche et luxueuse offre une hydratation intense qui dure 24 heures. Sa texture fondante pénètre rapidement sans laisser de film gras.',
    price: 64.99,
    image: getProductImagePath('Crème Hydratante Intense'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Essence Féminine',
    ingredients: 'Eau, Beurre de karité, Acide hyaluronique, Allantoïne, Huile d\'amande douce',
    usage: 'Appliquez matin et soir sur le visage et le cou en massant doucement.',
    skinType: ['Peau sèche', 'Peau normale', 'Peau mixte'],
    rating: 4.7,
    reviewsCount: 89,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '7',
    name: 'Crème Matifiante Peau Grasse',
    description: 'Contrôle du sébum et teint matifié toute la journée',
    longDescription: 'Crème légère formulée spécialement pour les peaux grasses. Contrôle le sébum, matifie le teint et hydrate sans surcharger.',
    price: 52.99,
    image: getProductImagePath('Crème Matifiante Peau Grasse'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Essence Féminine',
    skinType: ['Peau grasse', 'Peau mixte'],
    rating: 4.5,
    reviewsCount: 142,
    inStock: true
  },
  {
    id: '8',
    name: 'Crème Anti-Âge Collagène',
    description: 'Redensifie et repulpe la peau mature',
    longDescription: 'Crème anti-âge enrichie en peptides de collagène et élastine. Redonne fermeté, densité et éclat aux peaux matures.',
    price: 94.99,
    originalPrice: 129.99,
    image: getProductImagePath('Crème Anti-Âge Collagène'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Essence Féminine',
    skinType: ['Peau mature'],
    rating: 4.8,
    reviewsCount: 176,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '9',
    name: 'Crème Nourrissante Peau Sèche',
    description: 'Nourriture intensive pour peaux très sèches',
    longDescription: 'Crème ultra-riche aux beurres végétaux et huiles précieuses. Apaise, nourrit et répare les peaux sèches et déshydratées.',
    price: 58.99,
    image: getProductImagePath('Crème Nourrissante Peau Sèche'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Essence Féminine',
    skinType: ['Peau sèche'],
    rating: 4.6,
    reviewsCount: 108,
    inStock: true
  },
  {
    id: '10',
    name: 'Crème Nuit Régénérante',
    description: 'Régénération intensive pendant le sommeil',
    longDescription: 'Crème de nuit aux actifs régénérants qui travaillent pendant votre sommeil pour réveiller une peau lisse et repulpée.',
    price: 74.99,
    image: getProductImagePath('Crème Nuit Régénérante'),
    category: 'soins-visage',
    subCategory: 'Crèmes hydratantes',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.7,
    reviewsCount: 134,
    inStock: true
  },
  
  // SOINS DU VISAGE - Masques
  {
    id: '11',
    name: 'Masque Hydratant Aloe Vera',
    description: 'Hydratation flash pour un teint éclatant',
    longDescription: 'Masque gel à l\'aloe vera pur pour une hydratation instantanée. Parfait après une journée de soleil ou pour raviver le teint.',
    price: 34.99,
    image: getProductImagePath('Masque Hydratant Aloe Vera'),
    category: 'soins-visage',
    subCategory: 'Masques',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.5,
    reviewsCount: 167,
    inStock: true
  },
  {
    id: '12',
    name: 'Masque Argile Détox Purifiant',
    description: 'Purifie et nettoie les pores en profondeur',
    longDescription: 'Masque à l\'argile verte pour purifier les peaux grasses et mixtes. Absorbe l\'excès de sébum et nettoie les pores.',
    price: 32.99,
    image: getProductImagePath('Masque Argile Détox Purifiant'),
    category: 'soins-visage',
    subCategory: 'Masques',
    brand: 'Essence Féminine',
    skinType: ['Peau grasse', 'Peau mixte'],
    rating: 4.7,
    reviewsCount: 145,
    inStock: true
  },
  {
    id: '13',
    name: 'Masque Éclat Vitamine C',
    description: 'Éclat immédiat et teint unifié',
    longDescription: 'Masque éclaircissant à la vitamine C pour unifier le teint, réduire les taches et réveiller l\'éclat naturel de la peau.',
    price: 39.99,
    image: getProductImagePath('Masque Éclat Vitamine C'),
    category: 'soins-visage',
    subCategory: 'Masques',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.6,
    reviewsCount: 123,
    inStock: true
  },
  {
    id: '14',
    name: 'Masque Anti-Âge Collagène',
    description: 'Fermeté et repulpage immédiat',
    longDescription: 'Masque repulpant au collagène pour redonner fermeté et volume aux peaux matures. Effet lifting immédiat.',
    price: 44.99,
    image: getProductImagePath('Masque Anti-Âge Collagène'),
    category: 'soins-visage',
    subCategory: 'Masques',
    brand: 'Essence Féminine',
    skinType: ['Peau mature'],
    rating: 4.8,
    reviewsCount: 98,
    inStock: true
  },
  
  // SOINS DU VISAGE - Nettoyants
  {
    id: '15',
    name: 'Nettoyant Doux Mousse',
    description: 'Nettoyage en douceur sans décaper',
    longDescription: 'Mousse nettoyante douce qui nettoie en profondeur sans agresser. Respecte le pH naturel de la peau.',
    price: 24.99,
    image: getProductImagePath('Nettoyant Doux Mousse'),
    category: 'soins-visage',
    subCategory: 'Nettoyants',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.5,
    reviewsCount: 198,
    inStock: true
  },
  {
    id: '16',
    name: 'Gel Nettoyant Purifiant',
    description: 'Nettoie et purifie les peaux grasses',
    longDescription: 'Gel nettoyant aux actifs purifiants pour éliminer l\'excès de sébum et les impuretés. Formule non agressive.',
    price: 22.99,
    image: getProductImagePath('Gel Nettoyant Purifiant'),
    category: 'soins-visage',
    subCategory: 'Nettoyants',
    brand: 'Essence Féminine',
    skinType: ['Peau grasse', 'Peau mixte'],
    rating: 4.6,
    reviewsCount: 167,
    inStock: true
  },
  {
    id: '17',
    name: 'Huile Démaquillante Nourrissante',
    description: 'Démaquillage en douceur et hydratation',
    longDescription: 'Huile démaquillante qui dissout même le maquillage waterproof tout en nourrissant la peau. Texture légère et non grasse.',
    price: 29.99,
    image: getProductImagePath('Huile Démaquillante Nourrissante'),
    category: 'soins-visage',
    subCategory: 'Nettoyants',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.7,
    reviewsCount: 211,
    inStock: true,
    isBestSeller: true
  },
  
  // SOINS DU VISAGE - Protection solaire
  {
    id: '18',
    name: 'Crème Solaire SPF50+ Visage',
    description: 'Protection maximale au quotidien',
    longDescription: 'Crème solaire invisible SPF50+ pour une protection quotidienne optimale. Texture légère, non grasse, parfaite sous le maquillage.',
    price: 42.99,
    image: getProductImagePath('Crème Solaire SPF50+ Visage'),
    category: 'soins-visage',
    subCategory: 'Protection solaire',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.8,
    reviewsCount: 289,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '19',
    name: 'Fluide Solaire Teinté SPF30',
    description: 'Protection et teint unifié en un geste',
    longDescription: 'Fluide solaire teinté qui protège et unifie le teint. Parfait comme base de maquillage.',
    price: 38.99,
    image: getProductImagePath('Fluide Solaire Teinté SPF30'),
    category: 'soins-visage',
    subCategory: 'Protection solaire',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.6,
    reviewsCount: 156,
    inStock: true
  },
  
  // MAQUILLAGE - Fond de teint
  {
    id: '20',
    name: 'Fond de Teint Fluide Mat',
    description: 'Teint unifié et matifié longue tenue',
    longDescription: 'Fond de teint fluide à la couvrance ajustable pour un teint parfaitement unifié. Finition mat, tenue 12h.',
    price: 39.99,
    image: getProductImagePath('BB Crème Toute la Journée'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 312,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '21',
    name: 'BB Crème Toute la Journée',
    description: 'Hydratation, protection et teint parfait',
    longDescription: 'BB crème multi-fonctions qui hydrate, protège (SPF30) et unifie le teint. Texture légère, effet bonne mine naturel.',
    price: 34.99,
    originalPrice: 42.99,
    image: getProductImagePath('Correcteur Anti-Cernes Haute Couvrance'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 445,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '22',
    name: 'Correcteur Anti-Cernes Haute Couvrance',
    description: 'Camoufle les cernes et imperfections',
    longDescription: 'Correcteur haute couvrance qui camoufle efficacement les cernes, rougeurs et imperfections. Texture crémeuse, tenue parfaite.',
    price: 27.99,
    image: getProductImagePath('Poudre Matifiante Compacte'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Essence Féminine',
    rating: 4.9,
    reviewsCount: 567,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '23',
    name: 'Poudre Matifiante Compacte',
    description: 'Matifie et fixe le maquillage',
    longDescription: 'Poudre compacte ultra-fine pour matifier le teint et fixer le maquillage. Finition naturelle et veloutée.',
    price: 29.99,
    image: getProductImagePath('Highlighter Poudre Éclat'),
    category: 'maquillage',
    subCategory: 'Fond de teint',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 234,
    inStock: true
  },
  
  // MAQUILLAGE - Rouge à lèvres
  {
    id: '24',
    name: 'Rouge à Lèvres Velours',
    description: 'Couleur intense et tenue longue durée',
    longDescription: 'Notre rouge à lèvres velours offre une couleur intense et une tenue exceptionnelle. Enrichi en vitamine E pour des lèvres douces et hydratées.',
    price: 34.99,
    originalPrice: 39.99,
    image: getProductImagePath('Rouge à Lèvres Velours'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'Essence Féminine',
    rating: 4.9,
    reviewsCount: 256,
    inStock: true,
    isBestSeller: true,
    badges: ['Bestseller']
  },
  {
    id: '25',
    name: 'Rouge à Lèvres Liquide Matte',
    description: 'Finis mat longue tenue, 12h de couleur',
    longDescription: 'Rouge à lèvres liquide à la finition matte parfaite. Couleur intense, tenue exceptionnelle jusqu\'à 12h sans transfert.',
    price: 32.99,
    image: getProductImagePath('Rouge à Lèvres Liquide Matte'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 389,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '26',
    name: 'Baume à Lèvres Teinté',
    description: 'Hydratation et couleur naturelle',
    longDescription: 'Baume à lèvres teinté qui hydrate intensément tout en apportant une touche de couleur discrète et naturelle.',
    price: 19.99,
    image: getProductImagePath('Baume à Lèvres Teinté'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 412,
    inStock: true
  },
  {
    id: '27',
    name: 'Gloss Brillant Longue Tenue',
    description: 'Éclat et brillance jusqu\'à 8h',
    longDescription: 'Gloss haute brillance avec formule longue tenue. Texture non collante, effet miroir spectaculaire.',
    price: 28.99,
    image: getProductImagePath('Gloss Brillant Longue Tenue'),
    category: 'maquillage',
    subCategory: 'Rouge à lèvres',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 278,
    inStock: true
  },
  
  // MAQUILLAGE - Mascara
  {
    id: '28',
    name: 'Mascara Volume Intense',
    description: 'Cils volumineux et allongés instantanément',
    longDescription: 'Ce mascara révolutionnaire donne instantanément du volume et de la longueur à vos cils. Formule waterproof et résistante aux larmes.',
    price: 29.99,
    image: getProductImagePath('Mascara Volume Intense'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 178,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '29',
    name: 'Mascara Allongement Extrême',
    description: 'Cils XXL en un seul geste',
    longDescription: 'Mascara spécial allongement qui donne des cils XXL instantanément. Brosse fine et précise pour un effet naturel.',
    price: 27.99,
    image: getProductImagePath('Mascara Allongement Extrême'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 234,
    inStock: true
  },
  {
    id: '30',
    name: 'Mascara Waterproof Résistant',
    description: 'Tenue parfaite même dans l\'eau',
    longDescription: 'Mascara waterproof ultra-résistant qui ne coule pas même en pleurant ou à la piscine. Volume et longueur garantis.',
    price: 31.99,
    image: getProductImagePath('Mascara Waterproof Résistant'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 198,
    inStock: true
  },
  {
    id: '31',
    name: 'Mascara Cils Inférieurs',
    description: 'Précision pour les cils inférieurs',
    longDescription: 'Mascara mini spécialement conçu pour les cils inférieurs. Brosse ultra-fine pour une application précise et nette.',
    price: 22.99,
    image: getProductImagePath('Mascara Cils Inférieurs'),
    category: 'maquillage',
    subCategory: 'Mascara',
    brand: 'Essence Féminine',
    rating: 4.5,
    reviewsCount: 145,
    inStock: true
  },
  
  // MAQUILLAGE - Palettes
  {
    id: '32',
    name: 'Palette Fards à Paupières Nude',
    description: '12 nuances nudes pour tous les looks',
    longDescription: 'Palette complète de 12 fards à paupières dans les tons nudes, du plus clair au plus foncé. Formule ultra-pigmentée et facile à étaler.',
    price: 49.99,
    originalPrice: 64.99,
    image: getProductImagePath('Palette Fards à Paupières Nude'),
    category: 'maquillage',
    subCategory: 'Palettes',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 423,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '33',
    name: 'Palette Fards à Paupières Smoky',
    description: '10 nuances sombres pour yeux de braise',
    longDescription: 'Palette smoky eyes avec 10 nuances sombres et métalliques pour créer des looks intenses et glamour.',
    price: 52.99,
    image: getProductImagePath('Palette Fards à Paupières Smoky'),
    category: 'maquillage',
    subCategory: 'Palettes',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 312,
    inStock: true
  },
  {
    id: '34',
    name: 'Palette Complète Visage',
    description: 'Contour, blush et highlighter réunis',
    longDescription: 'Palette tout-en-un avec contour, blush et highlighter pour sculpter et illuminer le visage. 8 nuances harmonieuses.',
    price: 59.99,
    image: getProductImagePath('Palette Complète Visage'),
    category: 'maquillage',
    subCategory: 'Palettes',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 267,
    inStock: true
  },
  
  // MAQUILLAGE - Highlighter
  {
    id: '35',
    name: 'Highlighter Poudre Éclat',
    description: 'Illumination instantanée du teint',
    longDescription: 'Highlighter poudre ultra-lumineux pour sublimer les pommettes, l\'arête du nez et le front. Finition naturelle et éclatante.',
    price: 32.99,
    image: getProductImagePath('Highlighter Liquide Lumière'),
    category: 'maquillage',
    subCategory: 'Highlighter',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 289,
    inStock: true
  },
  {
    id: '36',
    name: 'Highlighter Liquide Lumière',
    description: 'Éclat liquide pour un effet wet look',
    longDescription: 'Highlighter liquide pour un effet "wet look" naturel. S\'applique sous ou sur le maquillage pour un éclat de star.',
    price: 29.99,
    image: getProductImagePath('Set Pinceaux Maquillage Pro'),
    category: 'maquillage',
    subCategory: 'Highlighter',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 198,
    inStock: true,
    isBestSeller: true
  },
  
  // SOINS DU CORPS - Lotions
  {
    id: '37',
    name: 'Lotion Corporelle Nourrissante',
    description: 'Hydratation profonde pour tout le corps',
    longDescription: 'Cette lotion corporelle luxueuse nourrit et hydrate votre peau en profondeur. Sa texture non grasse pénètre rapidement.',
    price: 39.99,
    image: getProductImagePath('Lotion Corporelle Nourrissante'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Essence Féminine',
    ingredients: 'Eau, Beurre de karité, Huile d\'argan, Glycérine, Parfum naturel',
    usage: 'Appliquez sur peau humide après la douche en massant jusqu\'à pénétration complète.',
    skinType: ['Tous types'],
    rating: 4.5,
    reviewsCount: 92,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '38',
    name: 'Lotion Hydratante Légère',
    description: 'Hydratation rapide et texture légère',
    longDescription: 'Lotion corporelle à la texture légère qui hydrate instantanément sans laisser de film gras. Absorption rapide.',
    price: 32.99,
    image: getProductImagePath('Lotion Hydratante Légère'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.6,
    reviewsCount: 156,
    inStock: true
  },
  {
    id: '39',
    name: 'Lotion Fermeté Anti-Âge Corps',
    description: 'Fermeté et élasticité pour le corps',
    longDescription: 'Lotion fermeté enrichie en collagène et élastine pour redonner tonus et élasticité à la peau du corps.',
    price: 44.99,
    image: getProductImagePath('Lotion Fermeté Anti-Âge Corps'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.7,
    reviewsCount: 134,
    inStock: true
  },
  {
    id: '40',
    name: 'Lotion Après-Soleil Apaisante',
    description: 'Soulage et hydrate après l\'exposition',
    longDescription: 'Lotion après-soleil rafraîchissante qui apaise, hydrate et prolonge le bronzage. Enrichie en aloe vera.',
    price: 36.99,
    image: getProductImagePath('Lotion Après-Soleil Apaisante'),
    category: 'soins-corps',
    subCategory: 'Lotions hydratantes',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.8,
    reviewsCount: 267,
    inStock: true
  },
  
  // SOINS DU CORPS - Huiles
  {
    id: '41',
    name: 'Huile Sèche Argan',
    description: 'Nourriture intense sans effet gras',
    longDescription: 'Huile sèche à l\'argan qui nourrit intensément sans laisser de film gras. Texture légère, pénétration rapide.',
    price: 54.99,
    image: getProductImagePath('Huile Sèche Argan'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.7,
    reviewsCount: 189,
    inStock: true
  },
  {
    id: '42',
    name: 'Huile Massage Relaxante',
    description: 'Détente et bien-être au quotidien',
    longDescription: 'Huile de massage aux huiles essentielles relaxantes pour un moment de détente. Texture fluide, parfum délicat.',
    price: 49.99,
    image: getProductImagePath('Huile Massage Relaxante'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.6,
    reviewsCount: 223,
    inStock: true
  },
  {
    id: '43',
    name: 'Huile Bronzante Naturelle',
    description: 'Bronzage progressif et uniforme',
    longDescription: 'Huile bronzante qui favorise un bronzage progressif et uniforme. Enrichie en huiles nourrissantes.',
    price: 42.99,
    image: getProductImagePath('Huile Bronzante Naturelle'),
    category: 'soins-corps',
    subCategory: 'Huiles',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.5,
    reviewsCount: 178,
    inStock: true
  },
  
  // SOINS DU CORPS - Gommages
  {
    id: '44',
    name: 'Gommage Corps Sucre de Coco',
    description: 'Exfoliation douce et parfumée',
    longDescription: 'Gommage corps aux grains de sucre de coco pour une exfoliation douce et efficace. Texture fondante au parfum gourmand.',
    price: 34.99,
    image: getProductImagePath('Gommage Corps Sucre de Coco'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.7,
    reviewsCount: 198,
    inStock: true
  },
  {
    id: '45',
    name: 'Gommage Corps Sel Marin',
    description: 'Exfoliation intensive pour peau lisse',
    longDescription: 'Gommage au sel marin pour une exfoliation plus intense. Idéal pour préparer la peau avant le bronzage ou pour lisser la peau.',
    price: 32.99,
    image: getProductImagePath('Gommage Corps Sel Marin'),
    category: 'soins-corps',
    subCategory: 'Gommages',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.6,
    reviewsCount: 145,
    inStock: true
  },
  
  // SOINS DU CORPS - Mains
  {
    id: '46',
    name: 'Crème Mains Réparatrice',
    description: 'Réparation intensive pour mains abîmées',
    longDescription: 'Crème mains ultra-riche qui répare, nourrit et protège les mains sèches et abîmées. Absorption rapide.',
    price: 18.99,
    image: getProductImagePath('Crème Mains Réparatrice'),
    category: 'soins-corps',
    subCategory: 'Soins des mains',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.8,
    reviewsCount: 312,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '47',
    name: 'Baume Mains SPF30',
    description: 'Hydratation et protection solaire',
    longDescription: 'Baume mains hydratant avec protection SPF30 pour protéger vos mains du vieillissement prématuré.',
    price: 22.99,
    image: getProductImagePath('Baume Mains SPF30'),
    category: 'soins-corps',
    subCategory: 'Soins des mains',
    brand: 'Essence Féminine',
    skinType: ['Tous types'],
    rating: 4.6,
    reviewsCount: 167,
    inStock: true
  },
  
  // CHEVEUX - Shampoings
  {
    id: '48',
    name: 'Shampoing Réparateur',
    description: 'Réparation intensive pour cheveux abîmés',
    longDescription: 'Notre shampoing réparateur restaure la santé et la brillance de vos cheveux. Enrichi en protéines et kératine.',
    price: 24.99,
    image: getProductImagePath('Shampoing Réparateur'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Essence Féminine',
    rating: 4.4,
    reviewsCount: 67,
    inStock: true
  },
  {
    id: '49',
    name: 'Shampoing Volume et Épaisseur',
    description: 'Donne du volume aux cheveux fins',
    longDescription: 'Shampoing spécialement formulé pour donner du volume et de l\'épaisseur aux cheveux fins et plats.',
    price: 26.99,
    image: getProductImagePath('Shampoing Volume et Épaisseur'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 189,
    inStock: true
  },
  {
    id: '50',
    name: 'Shampoing Hydratant Cheveux Secs',
    description: 'Hydratation profonde pour cheveux secs',
    longDescription: 'Shampoing nourrissant pour cheveux secs et déshydratés. Enrichi en huiles précieuses pour une hydratation maximale.',
    price: 25.99,
    image: getProductImagePath('Shampoing Hydratant Cheveux Secs'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 234,
    inStock: true
  },
  {
    id: '51',
    name: 'Shampoing Purifiant Cuir Chevelu',
    description: 'Nettoie en profondeur et purifie',
    longDescription: 'Shampoing purifiant qui nettoie en profondeur le cuir chevelu et élimine les résidus. Idéal pour cheveux gras.',
    price: 23.99,
    image: getProductImagePath('Shampoing Purifiant Cuir Chevelu'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Essence Féminine',
    rating: 4.5,
    reviewsCount: 156,
    inStock: true
  },
  {
    id: '52',
    name: 'Shampoing Colorant Cheveux Colorés',
    description: 'Préserve et fait briller les couleurs',
    longDescription: 'Shampoing spécial cheveux colorés qui préserve l\'intensité et l\'éclat de votre couleur. Formule douce.',
    price: 27.99,
    image: getProductImagePath('Shampoing Colorant Cheveux Colorés'),
    category: 'cheveux',
    subCategory: 'Shampoings',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 278,
    inStock: true,
    isBestSeller: true
  },
  
  // CHEVEUX - Après-shampoings
  {
    id: '53',
    name: 'Après-Shampoing Démêlant',
    description: 'Démêle et adoucit en un geste',
    longDescription: 'Après-shampoing démêlant qui facilite le brossage et adoucit les cheveux. Texture riche et nourrissante.',
    price: 24.99,
    image: getProductImagePath('Après-Shampoing Démêlant'),
    category: 'cheveux',
    subCategory: 'Après-shampoings',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 198,
    inStock: true
  },
  {
    id: '54',
    name: 'Masque Capillaire Intensif',
    description: 'Réparation et brillance en 5 minutes',
    longDescription: 'Masque capillaire intensif qui répare les cheveux abîmés et leur redonne brillance et douceur. Application 5 minutes.',
    price: 34.99,
    image: getProductImagePath('Masque Capillaire Intensif'),
    category: 'cheveux',
    subCategory: 'Masques',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 312,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '55',
    name: 'Masque Hydratant Cheveux Secs',
    description: 'Hydratation profonde pour cheveux secs',
    longDescription: 'Masque ultra-hydratant pour cheveux secs et déshydratés. Enrichi en huiles précieuses pour une hydratation maximale.',
    price: 32.99,
    image: getProductImagePath('Masque Hydratant Cheveux Secs'),
    category: 'cheveux',
    subCategory: 'Masques',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 267,
    inStock: true
  },
  
  // CHEVEUX - Soins coiffants
  {
    id: '56',
    name: 'Huile Capillaire Brillance',
    description: 'Brillance et protection de la pointe',
    longDescription: 'Huile capillaire légère qui apporte brillance et protège les pointes. S\'applique sur cheveux secs ou mouillés.',
    price: 29.99,
    image: getProductImagePath('Huile Capillaire Brillance'),
    category: 'cheveux',
    subCategory: 'Soins coiffants',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 345,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '57',
    name: 'Spray Thermoprotecteur',
    description: 'Protection contre la chaleur des appareils',
    longDescription: 'Spray thermoprotecteur qui protège les cheveux jusqu\'à 230°C lors de l\'utilisation du sèche-cheveux, lisseur ou fer à boucler.',
    price: 26.99,
    image: getProductImagePath('Spray Thermoprotecteur'),
    category: 'cheveux',
    subCategory: 'Soins coiffants',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 423,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '58',
    name: 'Laisse-in Brilliance et Volume',
    description: 'Style et tenue toute la journée',
    longDescription: 'Laisse-in qui apporte volume, brillance et tenue aux cheveux. Texture légère, effet naturel.',
    price: 27.99,
    image: getProductImagePath('Laisse-in Brilliance et Volume'),
    category: 'cheveux',
    subCategory: 'Soins coiffants',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 234,
    inStock: true
  },
  
  // PARFUMS
  {
    id: '59',
    name: 'Eau de Parfum Élégance',
    description: 'Fragrance florale et sophistiquée',
    longDescription: 'Eau de parfum aux notes florales et musquées pour une élégance intemporelle. Tenue longue, sillage envoûtant.',
    price: 89.99,
    image: getProductImagePath('Eau de Parfum Élégance'),
    category: 'parfums',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 456,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '60',
    name: 'Eau de Parfum Fraîcheur',
    description: 'Fragrance fraîche et légère',
    longDescription: 'Eau de parfum aux notes d\'agrumes et de fleurs blanches pour une fraîcheur quotidienne et légère.',
    price: 79.99,
    image: getProductImagePath('Eau de Parfum Fraîcheur'),
    category: 'parfums',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 389,
    inStock: true
  },
  {
    id: '61',
    name: 'Eau de Parfum Sensuelle',
    description: 'Fragrance orientale et envoûtante',
    longDescription: 'Eau de parfum aux notes orientales, vanille et ambre pour une sensualité envoûtante et mystérieuse.',
    price: 94.99,
    originalPrice: 119.99,
    image: getProductImagePath('Eau de Parfum Sensuelle'),
    category: 'parfums',
    brand: 'Essence Féminine',
    rating: 4.9,
    reviewsCount: 512,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '62',
    name: 'Eau de Toilette Légère',
    description: 'Fragrance douce et délicate',
    longDescription: 'Eau de toilette légère aux notes fruitées et florales pour une journée fraîche et délicate.',
    price: 64.99,
    image: getProductImagePath('Eau de Toilette Légère'),
    category: 'parfums',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 278,
    inStock: true
  },
  {
    id: '63',
    name: 'Eau de Parfum Romantique',
    description: 'Fragrance romantique et féminine',
    longDescription: 'Eau de parfum aux notes de rose et pivoine pour une féminité romantique et raffinée.',
    price: 84.99,
    image: getProductImagePath('Eau de Parfum Romantique'),
    category: 'parfums',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 334,
    inStock: true
  },
  
  // ACCESSOIRES BEAUTE
  {
    id: '64',
    name: 'Set Pinceaux Maquillage Pro',
    description: '15 pinceaux professionnels essentiels',
    longDescription: 'Set complet de 15 pinceaux professionnels pour un maquillage parfait. Qualité premium, poils synthétiques doux.',
    price: 79.99,
    originalPrice: 99.99,
    image: getProductImagePath('Éponge Beauté Maquillage'),
    category: 'accessoires',
    brand: 'Essence Féminine',
    rating: 4.8,
    reviewsCount: 567,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '65',
    name: 'Éponge Beauté Maquillage',
    description: 'Application parfaite du fond de teint',
    longDescription: 'Éponge beauté en mousse pour une application parfaite et uniforme du fond de teint. Texture douce, résultat naturel.',
    price: 12.99,
    image: getProductImagePath('Miroir Maquillage LED'),
    category: 'accessoires',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 823,
    inStock: true,
    isBestSeller: true
  },
  {
    id: '66',
    name: 'Miroir Maquillage LED',
    description: 'Éclairage professionnel pour un maquillage parfait',
    longDescription: 'Miroir de maquillage avec éclairage LED réglable pour un rendu professionnel. Pliable et portable.',
    price: 49.99,
    image: getProductImagePath('Étui à Pinceaux Premium'),
    category: 'accessoires',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 234,
    inStock: true
  },
  {
    id: '67',
    name: 'Étui à Pinceaux Premium',
    description: 'Rangez vos pinceaux en toute sécurité',
    longDescription: 'Étui élégant en cuir synthétique pour ranger et protéger vos pinceaux de maquillage. Fermeture zip, compartiments séparés.',
    price: 34.99,
    image: getProductImagePath('Gant Exfoliant Corps'),
    category: 'accessoires',
    brand: 'Essence Féminine',
    rating: 4.5,
    reviewsCount: 167,
    inStock: true
  },
  {
    id: '68',
    name: 'Gant Exfoliant Corps',
    description: 'Exfoliation douce et efficace',
    longDescription: 'Gant exfoliant en microfibre pour une exfoliation douce et efficace du corps. Réutilisable, lavable en machine.',
    price: 14.99,
    image: getProductImagePath('Bandeaux Cheveux Soie'),
    category: 'accessoires',
    brand: 'Essence Féminine',
    rating: 4.6,
    reviewsCount: 289,
    inStock: true
  },
  {
    id: '69',
    name: 'Bandeaux Cheveux Soie',
    description: 'Protège les cheveux pendant le sommeil',
    longDescription: 'Bandeau de sommeil en soie pour protéger vos cheveux des frottements et réduire les frisottis. Confortable et élégant.',
    price: 24.99,
    image: getProductImagePath('Palette Maquillage Vide'),
    category: 'accessoires',
    brand: 'Essence Féminine',
    rating: 4.7,
    reviewsCount: 198,
    inStock: true
  },
  {
    id: '70',
    name: 'Palette Maquillage Vide',
    description: 'Créez votre palette personnalisée',
    longDescription: 'Palette maquillage vide avec aimants pour créer votre palette personnalisée avec vos produits favoris.',
    price: 19.99,
    image: getProductImagePath('Palette Maquillage Vide'),
    category: 'accessoires',
    brand: 'Essence Féminine',
    rating: 4.5,
    reviewsCount: 145,
    inStock: true
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    productId: '1',
    userName: 'Sophie M.',
    rating: 5,
    comment: 'Excellent produit ! Ma peau est visiblement plus radieuse après seulement 2 semaines d\'utilisation.',
    date: '2024-01-15',
    verified: true
  },
  {
    id: '2',
    productId: '1',
    userName: 'Emma L.',
    rating: 5,
    comment: 'Je recommande vivement ce sérum. Texture agréable et résultats impressionnants.',
    date: '2024-01-10',
    verified: true
  },
  {
    id: '3',
    productId: '24',
    userName: 'Léa D.',
    rating: 5,
    comment: 'Ma couleur préférée ! Tenue exceptionnelle et texture très confortable.',
    date: '2024-01-20',
    verified: true
  },
  {
    id: '4',
    productId: '20',
    userName: 'Camille R.',
    rating: 5,
    comment: 'Fond de teint parfait ! Couvrance excellente et tenue toute la journée.',
    date: '2024-01-22',
    verified: true
  },
  {
    id: '5',
    productId: '37',
    userName: 'Marie K.',
    rating: 5,
    comment: 'Lotion super hydratante, ma peau est douce comme la soie !',
    date: '2024-01-18',
    verified: true
  },
];
